src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java
and clean up Some other NPEs
These are additional fixes related to https://github.com/jenkinsci/ec2-plugin/pull/106 that I found after submitting the PR. We have these running in production and haven't seen any problems related to the original report since.
=> Check more places where passing a null instanceID can do a search of random spot instances. 

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2Cloud.java, src/main/java/hudson/plugins/ec2/EC2PrivateKey.java, src/main/java/hudson/plugins/ec2/Eucalyptus.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/SpotConfiguration.java, src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java, src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java, src/main/java/hudson/plugins/ec2/win/winrm/RuntimeIOException.java, src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
No change in functionality, just some
imports reorganisation, deprecated method calls removal etc.
=> Code cleanup

src/main/java/hudson/plugins/ec2/win/WinConnection.java
…startup delay, use $IPC will skip the dfs check
=> ping connection tunning

src/main/java/hudson/plugins/ec2/EC2SlaveMonitor.java, src/main/java/hudson/plugins/ec2/EC2Tag.java, src/main/java/hudson/plugins/ec2/win/WinConnection.java, src/main/java/hudson/plugins/ec2/win/winrm/WinRM.java, src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java, src/main/java/hudson/plugins/ec2/win/winrm/WindowsProcess.java, src/main/java/hudson/plugins/ec2/win/winrm/request/DeleteShellRequest.java, src/main/java/hudson/plugins/ec2/win/winrm/request/ExecuteCommandRequest.java, src/main/java/hudson/plugins/ec2/win/winrm/request/GetOutputRequest.java, src/main/java/hudson/plugins/ec2/win/winrm/request/RequestFactory.java, src/main/java/hudson/plugins/ec2/win/winrm/request/SendInputRequest.java, src/main/java/hudson/plugins/ec2/win/winrm/request/SignalRequest.java, src/main/java/hudson/plugins/ec2/win/winrm/soap/Header.java, src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ImmutableField - Immutable Field
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:ImmutableField
M-Ezzat
=> pmd:ImmutableField - Immutable Field

pom.xml, src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2Cloud.java, src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java, src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java, src/main/java/hudson/plugins/ec2/EC2SpotSlave.java, src/main/java/hudson/plugins/ec2/PluginImpl.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/UnixData.java, src/main/java/hudson/plugins/ec2/WindowsData.java, src/main/java/hudson/plugins/ec2/ebs/ZPoolMonitor.java, src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java, src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
I found very strange that this plugin are still using JDK5, so, I updated some dependencies and removed unused one.
Also, I changed target version to 1.7 (JDK7).
=> Increase minimal supported version to 1.625.1 (to enable JDK7)

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2Cloud.java
Cleaning up the PR in #186 so it can be merged and the issue can be closed.
=> JENKINS-32915

src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
Fix the "Check AMI" and "Check Current Spot Price" buttons
=> Fix the "Check AMI" and "Check Current Spot Price" buttons

src/main/java/hudson/plugins/ec2/EC2Cloud.java
Change fixes JENKINS-36006 by checking for AMI ID and Jenkins Slave type tag
=> Fixed JENKINS-36006

src/main/java/hudson/plugins/ec2/EC2Cloud.java
It looks like spot instances were being double counted (at the instance level and then again for the spot instance request itself). This appears to fix it for me.
=> Avoid double counting spot instances

src/main/java/hudson/plugins/ec2/EC2Computer.java
Hi I had found a small mistake in Ec2Computer.java, fixed that issue please check once.
=> Did small correction in EC2Computre.java

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2Computer.java, src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/UnixData.java, src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java, src/main/resources/hudson/plugins/ec2/UnixData/config.jelly, src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java, src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Allow a user to input a slave prefix command that will be executed
before launching the slave jar.
=> Add slave prefix command

pom.xml, src/test/java/hudson/plugins/ec2/win/WinConnectionTest.java
@francisu @ndeloof as the current people declared in the permission file as releasers.
cc @reviewbybees for more eyes.
=> Bump to latest parent pom

.mvn/extensions.xml, .mvn/maven.config, pom.xml, src/test/java/hudson/plugins/ec2/win/WinConnectionTest.java
Based off https://github.com/jenkinsci/ec2-plugin/pull/289.
Only last commit is the intended addition here.
=> [JEP-305] Incrementalify

src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Reverts jenkinsci/ec2-plugin#276
=> Revert "Start agent in cygwin friendly way"

pom.xml
=> Update to AWS SDK 1.11.403

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2Computer.java, src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/UnixData.java, src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java, src/main/resources/hudson/plugins/ec2/UnixData/config.jelly, src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java, src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Allow a user to input a slave suffix command that will be executed
before launching the slave jar.
=> JENKINS-52828: Add slave suffix command

src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java, src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2Cloud.java, src/main/java/hudson/plugins/ec2/Eucalyptus.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly, src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly, src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java, src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
Merged changes from master and resolved conflicts.
=> [JENKINS-42530] Add support of switching role

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
This change always tags the attached volumes. Allowing a config option via UI obviously would require more changes.
=> JENKINS-39702: Tag volumes attached to an instance

src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- Added configuration option for templates to select T2 Unlimited.
=> JENKINS-48548: Add T2 Unlimited Support

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
It would allow to get information about instance type from groovy scripts
=> Add public getter for instanceType

src/main/java/hudson/plugins/ec2/EC2Cloud.java
There are multiple codepaths that can call connect(). Some codepaths
have already acquired the hudson.model.Queue lock, and others don't, so
the synchronized keyword here can lead to deadlocks where one thread is
holding the Queue lock and trying to lock the EC2Cloud, and another
thread is holding the EC2Cloud lock and trying to lock the Queue.
With the keyword removed, there's the possibility of multiple EC2
connections occurring, but I've yet to see this cause any observable
problems in reality, and the deadlock issue seems to have stopped
entirely.
We also move to a single purpose-built ReentrantLock per EC2Cloud
instance, since that codepath was one of the most common holders of the
EC2Cloud lock.
cc @thoulen
=> [JENKINS-53858] Remove synchronized from EC2Cloud.connect() to fix deadlock

src/main/java/hudson/plugins/ec2/EC2Cloud.java
Exclude stopped instance from the count of the CAP, the stopped instances are the first recovered, no problem for node leek
=> FIX JENKINS-54041

pom.xml, src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
Added support for [T3 instance types](https://aws.amazon.com/ec2/instance-types/t3/).
=> JENKINS-54536 - T3 instance type class support

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
This PR adds support for the new A1 instance types. It also includes the changes from #320 . I really wasn't sure what the right recommendations for number of executors should be so I guessed.
=> A1 instance types

src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/SpotConfiguration.java, src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Redo of https://github.com/jenkinsci/ec2-plugin/pull/273
=> Allow launching spot slaves without a bid price

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
=> JENKINS-54536: Allow all T3 types

pom.xml, src/main/java/hudson/plugins/ec2/EC2PrivateKey.java, src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly, src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly, src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
This provides a more secure UI component for entering multiline secret
values.
=> Use secretTextarea for private keys

src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Add default for maxTotalUses and for the connectionStrategy
=> Add default to the new fields

src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java, src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- Rename slaves where it makes sense to be more aligned with the rest of Jenkins
=> Rename slave to remoting or agent

src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Currently the volumes are not tagged together with instances this change is to rectify that.
=> Tag volumes and instances together

pom.xml
Add a plugin description which will show up in the plugin manager
=> Add plugin description

src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java, src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
Co-authored-by: Adrien Tateno <adrien.k.tateno@gmail.com>
We have scenarios where Jenkins needs to provision many new worker nodes on the scale of 100+ machines. See corresponding [Jira ticket](https://issues.jenkins-ci.org/browse/JENKINS-57161) detailing the observed behavior. After profiling Jenkins, we observed that as the EC2 instances spin up, let's say 60 of them, those instances' futures may finish during a single call to `NodeProvisioner.update()`. `Jenkins.updateComputerList` is then called for every instance that finishes, which calls `EC2RetentionStrategy.check()` for _every_ computer known to Jenkins, resulting in ~3000 synchronous AWS API calls and a multi-100 second lock for a single invocation of `NodeProvisioner.update()`. When this lock is held during …
=> Only periodically call internalCheck in EC2RetentionStrategy.

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
M5a support and fix the long lived TODO for m416xlarge
=> Add M5a instance support and correct M4

spotbugs-exclude.xml, src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java, src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2Computer.java, src/main/java/hudson/plugins/ec2/EC2PrivateKey.java, src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java, src/main/java/hudson/plugins/ec2/EC2SpotSlave.java, src/main/java/hudson/plugins/ec2/EC2Tag.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/SpotConfiguration.java, src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java, src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java, src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
Fixing the findbugs in the repository
Some changes would likely need exceptions thrown as I'm not sure if the function should ever be in that state.
=> [JENKINS-52208] Fix findbugs in repository

src/main/java/hudson/plugins/ec2/EC2Cloud.java, src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java, src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
- Fix NPE when `instanceCapStr` is null and add test for the same case
=> [JENKINS-57562] Fix NPE and add test

pom.xml, spotbugs-exclude.xml, src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java, src/main/java/hudson/plugins/ec2/win/WinConnection.java
This PR implements SMB2/3 support by leveraging SMBj. Unfortunately SMBj doesn't support SMB1 therefore this removes support for SMB1 also. Maybe it should be made backwards compatible or we should move off the old protocol.
=> [For Discussion] SMB2 Support

src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
related to https://jenkins.io/redirect/class-filter/
=> fix for java.lang.UnsupportedOperationException

src/main/java/hudson/plugins/ec2/SlaveTemplate.java
When working on the filter PR saw some minor cleanups worth doing
=> Cleanup slavetemplate

pom.xml, src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java, src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
Adding a Jcasc Export test for better jcasc coverage
=> Jcasc Export Test

pom.xml
- Bump to the latest plugin POM
=> Bump plugin POM to latest

src/main/java/hudson/plugins/ec2/EC2Cloud.java, src/test/java/hudson/plugins/ec2/EC2StepTest.java
https://github.com/jenkinsci/ec2-plugin/pull/296
=> Test case for the PR296

src/main/java/hudson/plugins/ec2/EC2Cloud.java
=> [JENKINS-53858] fix implementation of double-check-locking

src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
I've been working on [JENKINS-53322], preparing to eliminate the Jenkins fork of dom4j and switch to the latest, standard release, 2.1.1. The ec2 plugin has a couple of minor compilation failures with 2.1.1.
This PR makes a couple of small tweaks to enable it to compile on the version it has been using and 2.1.1. To test it on current, just compile with this change. To test it with 2.1.1, add a dom4j dependency to the pom, as shown here: [2.1.1](https://mvnrepository.com/artifact/org.dom4j/dom4j/2.1.1).
I'm hoping to land the switch in Jenkins within the next few weeks. Without this change in the ec2-plugin, it will fail when that occurs. This change can go in before that time.
=> [JENKINS-53322] Cross-version dom4j compatibility tweaks.

src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
Missed out windows on the same fix as #373
=> Fix workdir on windows

pom.xml
- Trilead is going to be removed from core at some point we use it so adding it as a dependency
=> Add trilead as a dependency

pom.xml
- Increment SDK dependency for users to see the new instance types
- Increment JCasC version to always test against more recent versions
=> Increment dependencies

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2PrivateKey.java, src/main/java/hudson/plugins/ec2/WindowsData.java, src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java, src/main/resources/hudson/plugins/ec2/WindowsData/config.jelly, src/test/java/hudson/plugins/ec2/EC2PrivateKeyTest.java
Adds a new option, might want to disable adding the password manually when checkbox is selected
=> Add support for retrieving the windows password admin automatically

pom.xml
- Pickup newer versions of dependencies for fixes and new instance types
=> Dependency bump

src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
Fix sleep time to match log message
=> Fix typo for sleep time

src/main/java/hudson/plugins/ec2/EC2PrivateKey.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java, src/main/java/hudson/plugins/ec2/win/winrm/request/SendInputRequest.java
Standardize to a single implementation.
=> Replace base64 implementation with java provided one

TODO.txt
=> Remove todo

src/main/java/hudson/plugins/ec2/EC2PrivateKey.java, src/test/java/hudson/plugins/ec2/EC2PrivateKeyTest.java
https://issues.jenkins-ci.org/browse/JENKINS-59633
=> [JENKINS-59633] delete new lines in encrypted windows password

pom.xml
These all needs to be bumped as they are blocking #425
=> bump parent pom, aws sdk, apache http client

src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/UnixData.java, src/main/java/hudson/plugins/ec2/win/winrm/request/OpenShellRequest.java, src/main/resources/hudson/plugins/ec2/Messages.properties, src/test/java/hudson/plugins/ec2/ConnectionStrategyTest.java, src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java, src/test/java/hudson/plugins/ec2/util/EC2AgentFactoryMockImpl.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Cleanup some of the old code
=> Misc cleanups

Jenkinsfile
=> Use ACI agents

README.md, src/main/java/hudson/plugins/ec2/EC2Cloud.java, src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
This PR provides some minor editorial changes (wording, missing hyphens, acronyms, etc) to the main README, plus fixing the legacy broken Eucalpytus link.
It also fixes a minor typo in a LOGGING output.
=> Editorial changes

pom.xml
Supersedes #436 due to upperbound deps errors in it
=> Pom updates

pom.xml
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
This new dependency was added in `1.50.2` security release
=> Use common-compress from core

Jenkinsfile
Instead of wrestling with the library lets just be explicit for now.
=> Be explicit about build configurations

README.md
Easy PR to fix the TOC
@res0nance @fcojfernandez
=> Fix toc because of downgrade issue

.dependabot/config.yml
I was wondering why the bot kept asking me about this!
=> Remove jvz from dependabot reviewers

src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
Adding an ssh credential test as there doesn't seem to be one right now
=> Add an ssh credential test

src/main/java/hudson/plugins/ec2/EC2Cloud.java
Keys with BEGIN OPENSSH PRIVATE KEY are also valid
Reported on mailing list: https://groups.google.com/g/jenkinsci-users/c/GwDegE_BdMg
- [N/A] Link to relevant issues in GitHub or Jira
- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
- [?] Ensure you have provided tests - that demonstrates feature works or fixes the issue
I don't know how to write a test for this pull request, feel free to educate me in the comments.
=> SSH key check is too strict

src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java, src/test/resources/hudson/plugins/ec2/MacDataExport.yml
=> Fix failing tests

src/main/java/hudson/plugins/ec2/EC2Cloud.java
=> Fallback on other templates if provisioning fails

src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
Ticket with the description of the issue: [JENKINS-64738](https://issues.jenkins.io/browse/JENKINS-64738)
Original PR: [543](https://github.com/jenkinsci/ec2-plugin/pull/543)
=> [JENKINS-64738] Fixed typo in dropdownListBlock attribute name

src/test/java/hudson/plugins/ec2/util/DeviceMappingParserTest.java
=> Enable device mapping tests

src/main/java/hudson/plugins/ec2/SlaveTemplate.java
=> Fix connection strategy warning for new templates

src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
=> [JENKINS-65569] Prevent invalid names for agents

src/main/java/hudson/plugins/ec2/win/WinConnection.java
Workaround for https://github.com/hierynomus/smbj/issues/638 till the fix is in a release
=> Set SecurityProvider for SMB

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java, src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/util/EC2AgentConfig.java, src/main/java/hudson/plugins/ec2/util/EC2AgentFactoryImpl.java, src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly, src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly, src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-metadataEndpointEnabled.html, src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-metadataHopsLimit.html, src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-metadataTokensRequired.html, src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java, src/test/resources/hudson/plugins/ec2/MacDataExport.yml, src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpoint.yml, src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
Add metadata configuration options in the Advanced section
=> [JENKINS-65127] Support IMDSv2 configuration

src/main/java/hudson/plugins/ec2/win/WinConnection.java
Socket art not getting closed when windows agent get closed! This caused an error `jenkins too many open files` after running jenkins without a restart for one week allocating and deallocating about 1000 windows agent.
I noticed this by running the command:
`sudo lsof -u jenkins | grep sock | wc -l` 
Number of socket kept increasing even after deleting all windows agents. It reached more than 4000 open socket.
After a jenkins restart, number of open socket fall down to 20.
=> fixed socket leak, properly close all connections

src/test/java/hudson/plugins/ec2/EC2StepTest.java
Terminology cleanup related to https://github.com/jenkinsci/jenkins/pull/5425
cc @res0nance
=> make unit tests compatible with Jenkins 2.307+

pom.xml
See https://github.com/jenkinsci/ec2-plugin/pull/659#issuecomment-931473227
=> update aws-sdk to 11.12.70

src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-customDeviceMapping.html
=> doc: add docs for throughput parameter

src/main/java/hudson/plugins/ec2/win/WinConnection.java
We are currently on the latest version and no longer need
that workaround any longer
=> win: cleanup workaround for smbj

src/main/java/hudson/plugins/ec2/win/WinConnection.java
TransportException can occur due to caching in smbj
unregister and try again when that happens
=> [JENKINS-66736] win: retry connection on transportexception

pom.xml
Updates the plugin parent POM and BOM to the latest versions.
=> Refresh plugin metadata

src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
add support for instance type dl1
=> add instance type dl1

src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java, src/main/java/hudson/plugins/ec2/CloudHelper.java, src/main/java/hudson/plugins/ec2/EC2Cloud.java, src/main/java/hudson/plugins/ec2/EC2Filter.java, src/main/java/hudson/plugins/ec2/EC2SpotSlave.java, src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/main/java/hudson/plugins/ec2/util/Closeables.java, src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java, src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java, src/test/java/hudson/plugins/ec2/util/AmazonEC2FactoryMockImpl.java
Compatible with [plugin POM 4.32](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.32).
=> EOL JSR 305

pom.xml
=> pom: remove instance-identity dep

src/main/java/hudson/plugins/ec2/ssh/verifiers/CheckNewHardStrategy.java
=> verifiers: Make hard strategy try for at least 2 minutes

Jenkinsfile
=> Test with java 17

src/main/java/hudson/plugins/ec2/win/SelfSignedCertificateAllowedMonitor.java
[JENKINS-69348](https://issues.jenkins.io/browse/JENKINS-69348): this message "Dismiss" button was a no-op from this monitor perspective.
=> [JENKINS-69348] Properly disable the monitor when hitting Dismiss

src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java, src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
=> launcher: check if host is empty or null

.github/workflows/jenkins-security-scan.yml
=> Enable security scan

pom.xml, src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
=> Update pom to 4.50

Jenkinsfile, pom.xml
=> Upgrade baseline to the latest LTS

pom.xml
=> pom: update aws-sdk and fix upper dep error

pom.xml
=> pom: update plugin-pom to 4.58

pom.xml
=> Update aws sdk to 1.12.529-406.vdeff15e5817d

pom.xml
=> Update jenkins baseline to 2.414.3

src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Change description: Added tagging for a Node's Networking Interface, previously only the provisioned instance and it's EBS volume were tagged. 
No tests were added for this, as from what I saw there were no tests for the instance and volume tagging and it seemed pointless to mock such a cosmetic change.
=> Added tagging for Instance Network Interface

pom.xml
=> Update jenkins baseline to 2.452.4

src/main/java/hudson/plugins/ec2/SlaveTemplate.java
It can be quite tricky to troubleshoot the behavior of the EC2 Plugin in regards to the lookup up of Security Groups. Propose some additional FINE loggers to help troubleshoot it.
N/A
=> Adding FINE logging in SG lookups for easier troubleshooting

src/main/java/hudson/plugins/ec2/EC2Cloud.java
=> Fix Spotless

src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
[JENKINS-75098](https://issues.jenkins.io/browse/JENKINS-75098)
- Log exceptions from EC2 RunInstances call
Added unit test to cover the new code.
=> JENKINS-75098:Log EC2 errors while calling RunInstances for reserved capacity

src/main/java/hudson/plugins/ec2/SlaveTemplate.java, src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
[JENKINS-75098](https://issues.jenkins.io/browse/JENKINS-75098)
Update log message from EC2 RunInstances call to include number of nodes requested
Ran unit test that covers the new code.
=> Update log message from EC2 RunInstances call to include number of nodes requested

src/main/java/hudson/plugins/ec2/util/AmazonEC2FactoryImpl.java
https://github.com/jenkinsci/ec2-plugin/pull/1044#pullrequestreview-2669214811
=> Partial revert of #1044

src/main/java/hudson/plugins/ec2/win/WinConnection.java, src/main/resources/hudson/plugins/ec2/Messages.properties, src/test/java/hudson/plugins/ec2/win/WinConnectionWithFIPSTest.java
The plugin is wrapping the `com.hierynomus:smbj` library, which implements the Windows Server Message Block Protocol and includes NT LanMan authentication (NTLM). NTLM is not FIPS-140 approved and this is an issue if Jenkins runs on FIPS mode.
This library is used in the `WinConnection` class, therefore, in FIPS mode this class cannot be instantiated.
Windows agent cannot be used if configured with winrm. As an alternative, use an ssh server and the `UnixLauncher`:
* Enable SSH server (https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui&pivots=windows-server-2025).
* Use the "UNIX" template
* The plugin will be able to connect to the Windows machine using Mina SSH, but an init script must not be used as it will create a `.sh` file
* If …
=> Do not allow Win NTLM connections in FIPS mode

src/main/java/hudson/plugins/ec2/EC2Computer.java
https://issues.jenkins.io/browse/JENKINS-75491
Add instance ID to getDecodedConsoleOutputResponse
In PR: https://github.com/jenkinsci/ec2-plugin/pull/1021
`GetConsoleOutputRequest request = new GetConsoleOutputRequest(getInstanceId());`
was replace with
`GetConsoleOutputRequest.Builder requestBuilder = GetConsoleOutputRequest.builder();`
leaving out the instance Id
`mvn clean verify`
Tested on Jenkins controller 2.503
=> [JENKINS-75491] Add Instance Id to getDecodedConsoleOutputResponse

src/main/java/hudson/plugins/ec2/SlaveTemplate.java
=> add default for enclaveEnabled in readResolve()

.vscode/settings.json, src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java, src/test/java/hudson/plugins/ec2/ssh/InitScriptExecutionTest.java
This PR attempts to do proper error handling around execution of init script, so that the plugin can prevent launching of a faulty EC2 agent.
We need this change because init script is used to prepare the EC2 agent with some pre-requisites with all necessary dependencies to execute a Jenkins job. If init script fails to execute successfully it implies all dependencies haven't been satisfied, in such case the EC2 agent even if it is launched will be a faulty one as it will be unable to successfully execute the jobs. So in case if the init script fails then the EC2 agent should also be prevented from getting launched and should be terminated.
This changes has been tested on a running Jenkins instance at version `2.470.3`. The test screenshots with some masked details are attached with this …
=> Prevent launching of ec2 nodes on init script failure

src/main/java/hudson/plugins/ec2/EC2Computer.java
Fix a slight issue introduced in https://github.com/jenkinsci/ec2-plugin/pull/1021
* start a job
* wait for EC2 agent to be provisioned
* validate that the uptime is correct
=> [JENKINS-75687] Fix Computer uptime
