jenkinsci/ec2-plugin

- pom.xml
* upgrade aws-java-sdk ot version 1.9.24
https://issues.jenkins-ci.org/browse/JENKINS-26414
> JENKINS-26414 - Add support for new C4 instance types

- pom.xml
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
* fixing error code for provisionOndemand - InvalidInstanceID.NotFound
* refactoring updateRemoteTags - no code duplication
* no exception throwing if remote tagging fails - only logging
** otherwise we got zombie instances which are not shown
* adding unit testing
https://issues.jenkins-ci.org/browse/JENKINS-26797
> JENKINS-26797 - Zombie instance created by the EC2 plugins

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
When there is a ssh connection issue currently there is not any `e.getMessage()` which shows more information about the issue.
Also, it might be nice to explicitly say that you are using the Proxy HTTP settings since there is not any documentation at level user which says that it will work in this way. It will also provide some hints to troubleshooting in case there is a ssh issue with EC2.
> Add more logging to ssh launcher

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
I cleaned up the on calls to log the launch of on demand and spot instances so that they are now the same format and also now both make the same calls, previously provisionSpot was missing the call to LOGGER.info
> Small cleanup in logging statements

- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
As per [Jenkins-27260](https://issues.jenkins-ci.org/browse/JENKINS-27260):
JENKINS-25385 and JENKINS-4995 both have comments complaining about infinite loops when creating Windows slaves. Because SPNEGO is unregistered for, the httpclient throws an exception that is silently
caught and causes the infinite loop. 
I was able to connect to WinRM, but I had to re enable SPNEGO. I'm not sure what repercussions that will have otherwise, I'm hoping someone can comment on that. 
I also found that the tmpDir was getting set to "", causing a failure, so I added in a case for that.
> [JENKINS-27260] SPNEGO for Windows in EC2 Plugin

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/EC2Cloud/computerSet.jelly
- src/main/resources/hudson/plugins/ec2/Messages.properties
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
Originally cloud id was derived from the region, which prevented
creating more than one cloud per region.
With this patch I made cloud name visible and configurable,
effectively allowing multiple clouds per region.
Also, "Provision via EC2" buttons in /computer view now have
cloud name instead of "EC2"
All changes are backwards compatible
> JENKINS-24359: Overcoming limit of one cloud per region.

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2ComputerLauncher.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-connectBySSHProcess.html
We (at CloudBees) encountered a situation where the SSH connection would be mysteriously lost between the master and a slave agent running on EC2. This usually happened during long running jobs but we were unable to track down the root cause of the problem. How we worked around it was to make a change to the EC2 plugin (the changes in this PR) such that the plugin would connect to the slave agent via an external ssh client process that the plugin would launch (Vs using the Trilead lib).
Things that probably need to be resolved:
* This new option will only work where the master has an SSH client installed. Is it OK to just call this out as a limitation in `help-connectBySSHProcess.html`, or should we perform some runtime checks before offering it. The later would obviously be best but …
> [WiP] Launch slave agent via ssh client process

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
The configurable tmpdir (https://github.com/jenkinsci/ec2-plugin/commit/716497f3df642a3e0df097ce05364213179bbb88) broke automatic java download and install because it omitted a slash between /tmp and the jdk name.  The result was permission denied:
```
Creating tmp directory (/tmp) if it does not exist
Verifying that java exists
bash: java: command not found
Installing Java
/tmpjava1.6.0_12.tgz: Permission denied
Failed to download Java
```
By the looks of it, https://github.com/jenkinsci/ec2-plugin/commit/716497f3df642a3e0df097ce05364213179bbb88 may have done the same thing on Windows.
> Fix java download/install

- pom.xml
I am running Jenkins 1.609 on Fedora 21 with ec2-plugin 1.27. Fedora includes BouncyCastle 1.50, which drops the org.bouncycastle.openssl classes required by ec2-plugin 1.27. ec2-plugins includes the older version of BouncyCastle, 1.40, but the system version overrides it. So I set maven to include plugin libraries and classes in the Classpath version during compile. Along with explicitly masking org.bouncycastle.
This fixes the issue I had where it would error on use of the "Test Connection" button in "Configure System". It would try to load "org/bouncycastle/asn1/DERObject" for the "EC2 Key Pair's Private Key".
> Masking BouncyCastle for when the system verison is incompatiable with the required version

- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
The 'Check AMI' and 'Check Current Spot Price' buttons  currently do not work when instance profile credentials are used.
> Fixing instance profile credentials with 'Check AMI' and 'Check Current Spot Price' buttons 

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
Creates an AmazonEC2Client with an AWSCredentialsProvider instead of the AWSCredentials directly. This is done so the credentials will refresh instead of expire. Resolves JENKINS-26854.
At the moment, in EC2Cloud we create an AmazonEC2Client by passing in the credentials directly. This creates a StaticCredentialsProvider using the given credentials. StaticCredentialsProvider never refreshes its credentials, leading to expiration. Instead, you can create an AmazonEC2Client with a credentials provider directly. This refreshes the credentials as needed.
See http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-roles.html for more information.
> JENKINS-26854: Fixing 'RequestExpired'

- src/main/java/hudson/plugins/ec2/win/WinConnection.java
The configuration for Windows OnDemand slaves in EC2 is very fragile (security groups have to be configured *just right* in both the master and slaves, firewalls need to be set up correctly, etc). 
The ping implementation in WinConncetion basically hides the errors it sees, even though these may be critical to understanding connection problems.
> Don't hide connection errors

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
This is a proposed fix for JENKINS-28268
At FreshBooks, we have multiple Packer jobs that build new Jenkins build workers as and when the underlying repos are updated. The problem with this approach (currently) is that after this is done, someone needs to go in and manually update the Jenkins configuration to point to the new AMI ID.
With this approach, we could trigger a post-build Groovy script to automatically go in and update the relevant AMI ID without us having to do this manually.
Here is an example Groovy script that demonstrates getting and setting the AMI ID programatically:
```
import jenkins.model.*;
import hudson.plugins.ec2.*;
Jenkins.instance.clouds.each {
if (it.displayName == 'test-cloud') {
it.getTemplates().each {
println(it.displayName)
println("Print current AMI id : …
```
> Add the ability to programatically update the AMI ID using Groovy

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
In our production environment we get throttled by EC2 quite a lot. This can cause number of issues (e.g. slaves are not starting properly).
The default settings (3 retries, first wait 500 ms, second 1000ms) are fairly low for this use case. 
Extending retry to 16 (by default we have exponential wait times, with 20s maximum wait). It's better to slow down than to fail.
> Fix JENKINS-26800 by retrying more times on throttled requests

- pom.xml
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/EC2Slave/help-ebsOptimized.html
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
- src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
Adds a check box to allow for launching EBS-Optimized slaves.
Bumps aws sdk from 1.10.0 to 1.10.2
Wasn't sure about the appropriate formatting as there seems to be a mix :)
```
Results :
Tests run: 53, Failures: 0, Errors: 0, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:52 min
[INFO] Finished at: 2015-07-02T10:50:07-07:00
[INFO] Final Memory: 54M/445M
[INFO] ------------------------------------------------------------------------
```
> Add option to launch EBS-Optimized instances

- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-initScript.html
Hello,
Today I've spent quite a much time on debugging, why my init script does not work for certain EC2 build slaves. After reading the code  I've found magic happening with ` ~/.hudson-run-init`, which I could not find in documentation. And true, I've built that AMIs from instance already containing `.hudson-run-init` file.
I guess that this might be handy when slave reconnecting happens, but on the other hand, I'd rather expect such a provisioning script to be idempotent.
It's not like I'm forcing my solution with removal here, but for sure this magic file presence should be either covered in documentation or handled from UI (`do not run within reconnect` flag under init script text field)...
Please let me know what do you think, I'd be happy to collaborate on handling this!
> Magic file preventing from init script launch

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Currently instance caps are calculated solely based on AMI, not based on template. So, if there are two types of slaves based on a common AMI 
but intended for different purpose, if the instance cap is low on one type, it may never get provisioned if the other type has many outstanding instances.
Fixed the issue by appending template description as well to tag 'jenkins_slave_type' so that number of instances per template can be identified.
If you want to track using a new tag instead of appending template description to tag 'jenkins_slave_type', please let me know.
> fix for instance caps which are calculated solely based on AMI ID

- pom.xml
I've noticed that the aws sdk is getting used in various Jenkins plugins so I created a library plugin to host it and prevent duplicating the classpath. This pull request just unbundles the library from the ec2-plugin.
@reviewbybees
> Depend on the aws-java-sdk plugin to limit aws sdk duplication in classpath

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/resources/hudson/plugins/ec2/EC2Cloud/help-ec2EndpointUrl.html
Every region seems to support the format ec2.<region>.amazonaws.com:
http://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region
Disclaimer: I did not compile or test this change.
> Use new EC2 API endpoint hostnames (JIRA-26493)

- src/main/java/hudson/plugins/ec2/win/winrm/NegotiateNTLMSchemaFactory.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
- src/test/java/hudson/plugins/ec2/win/WinConnectionTest.java
The Default SPNEGO implementation in Httpclient is Kerbose, we can not use it on  Windows workstation which haven't joined Domain yet. the pull request enables NTLM response with the Integrated Authentication (WWW-Authenticate: Negotiate)
> NTLM with SPNEGO

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
This solved the authorization problem with the eu-central-1 region.
Have also bumped the AWS SDK version.
> Use AWS4SignerType instead of QueryStringSignerType

- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
Every time after Jenkins reboot the status of the Windows slave server's status is incorrect saying "Timed out after 0 seconds of waiting for winrm" and jobs are pending in the queue and cannot be executed.
> bugfix: add minimum timeout for windows launching

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
Fixes an issue where checking for uptime of a deleted node would cause an NPE.
Also fixes an issue when terminating spot instances. The new behavior will remove the node from Jenkins even if EC2 termination failed. One way for this issue to occur is that an instance was terminated manually or a spot instance was killed due to pricing. In these cases termination will fail, but the node will hang around in Jenkins forever. If we don't remove the node, we screw up auto-scaling, since it will continue to count against the quota.
> Fix NullPointerException when deleting already terminated slave

- src/main/java/hudson/plugins/ec2/EC2PrivateKey.java
- src/main/java/hudson/plugins/ec2/EC2Tag.java
- src/main/java/hudson/plugins/ec2/UnixData.java
- src/main/java/hudson/plugins/ec2/WindowsData.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2162 - equals methods should be symmetric and work for subclasses
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2162
M-Ezzat
> squid:S2162 - equals methods should be symmetric and work for subclasses

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - Collection.isEmpty() should be used to test for emptiness
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1155
M-Ezzat
> Staging/collection.is empty() should be used to test for emptiness

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
EC2UnixLauncher.bootstrap retry loop was broken by Connection.authenticate IOExceptions (Publickey auth failed for example)
> EC2UnixLauncher can survive Connection IOExceptions

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
You can not provision a new node when an existing node from the template
is marked offline.  This change consults isOffline() to allow new node
provisioning.  Nodes can either be offline due to channel errors or user
interaction.  Either way, don't block new nodes.
> JENKINS-33945 allow node provisioning when matching node is offline

- src/main/java/hudson/plugins/ec2/EC2Tag.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2259 - Null pointers should not be dereferenced
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2259
M-Ezzat
> squid:S2259 - Null pointers should not be dereferenced

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Rather than create another variable to set the instance initiated shutdown behaviour I reused the stopOnTerminate flag - which I think ensures consistency and a simpler solution.
I believe this fixes JENKINS-26371
Mark
> JENKINS-26371 - Ensure instance initiated shutdown behaviour is consistent with stopOnTerminate flag

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
on rare occasions, AWS may return fault instance which shows running in AWS console but can not be connected, need terminate such fault instance by STARTUP_TIMEOUT
> need remove fault instance

- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1192 - String literals should not be duplicated
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1192
M-Ezzat
> squid:S1192 - String literals should not be duplicated

- pom.xml
- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Computer.java
- src/main/java/hudson/plugins/ec2/Eucalyptus.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/EC2Cloud/help-credentialsId.html
- src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/Messages.properties
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2InstanceTypesTest.java
- src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2PrivateKeyTest.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
- src/test/java/hudson/plugins/ec2/util/DeviceMappingParserTest.java
Use centralized AWS credentials to manage the IAM access key in the Jenkins Credentials Store and allow to reuse the credentials in other plugins, help auditing configuration changes... (See screenshot 1)
Additional enhancement: if no IAM Credentials have been defined, use the standard AWS credentials resolution mechanism (see [DefaultAWSCredentialsProviderChain](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) and screenshot 2):
* Environment Variables - `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (RECOMMENDED since they are recognized by all the AWS SDKs and CLI except for .NET), or `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` (only recognized by Java SDK)
* Java System Properties - aws.accessKeyId and aws.secretKey
* …
> Use AWS credentials to manage the IAM access key

- src/main/java/hudson/plugins/ec2/util/DeviceMappingParser.java
- src/main/java/hudson/plugins/ec2/win/winrm/soap/Namespaces.java
- src/test/java/hudson/plugins/ec2/ListRegions.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118
M-Ezzat
> squid:S1118 - Utility classes should not have public constructors

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/SpotConfiguration.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-bidType.html
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
With slaves now being fully controlled by Jenkins master, there is no longer a need to be able to set "persistent" spot bids--in fact it's dangerous because it will cause "zombie" spot instances to be auto-created by AWS which are not visible to Jenkins!
> JENKINS-34671 - Remove spot request bid type setting

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Sorry if this isn't the right process, and happy to take direction about what to do better. I just noticed that choosing the "useEphemeralDrives" checkbox for my spot instances wasn't having the effect I expected. I was seeing only a single ephemeral volume being automounted.
> Create block device mappings for both ondemand and spot slaves

- src/main/resources/hudson/plugins/ec2/EC2Computer/help-idleTerminationMinutes.html
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-idleTerminationMinutes.html
I was so confused by the documentation in `src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-idleTerminationMinutes.html` (which shows up on the Manage Jenkins page) on what negative idle times do that I consulted the source code to understand what it meant. This pull request is my attempt to clarify that documention.
I've also documented that the idle termination time is also used to determine how frequently a node is checked for idleness. As part of that I made a guess (based on my observation of behaviour) as to from when and how frequently the plugin checks when a negative idle time is specified -- that's the sentence "_If it has an idle timeout of -5 it will first be checked at 11:55, and then continuously until 12:00_". I'm particularly unsure about the "continuously".
> Clarifies documentation of negative idle termination times.

- pom.xml
Resolves JENKINS-33196 - Add g2.8xlarge to the list of instance types.
> Update aws-java-sdk version to 1.10.50.

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2PrivateKey.java
- src/test/java/hudson/plugins/ec2/EC2PrivateKeyTest.java
[JENKINS-35457](https://issues.jenkins-ci.org/browse/JENKINS-35457)
Dependency to multiple Bouncy Castle versions from jenkins core and plugins is causing problems due to the binary incompatibility between versions, the different supported algorithms, etc.
Plugins should be migrated to use a common API and BC version in order to avoid these problems, see [bouncycastle-api plugin](https://github.com/jenkinsci/bouncycastle-api/blob/master/README.md)
@reviewbybees
> [JENKINS-35457] Migrate from using bouncy castle to bouncycastle-api plugin

- pom.xml
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/EC2Cloud/computerSet.jelly
- src/main/resources/hudson/plugins/ec2/EC2Cloud/config.jelly
- src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
- src/main/resources/hudson/plugins/ec2/EC2SpotComputerLauncher/main.properties
- src/main/resources/hudson/plugins/ec2/EC2Tag/config.jelly
- src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/ebs/ZPoolExpandNotice/index.jelly
- src/main/resources/hudson/plugins/ec2/ebs/ZPoolExpandNotice/message.jelly
- src/main/resources/index.jelly
Upgraded to plugin-pom 2.11 and raised core version to 1.648 to avoid having to update from BC API 1.0 to 1.648 as requested on [JENKINS-36197](https://issues.jenkins-ci.org/browse/JENKINS-36197)
> [JENKINS-36197] Upgrade to plugin-pom 2.11

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2ComputerLauncher.java
- src/main/java/hudson/plugins/ec2/EC2Tag.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/main/java/hudson/plugins/ec2/win/WinConnection.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRM.java
This pull request is focused on resolving occurrences of Sonar rules squid:S00117 - Local variable and method parameter names should comply with a naming convention
squid:S2325 - "private" methods that don't access instance data should be "static"
You can find more information about the issues here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S00117
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2325
M-Ezzat
> squid:S00117, squid:S2325 - Multiple quality improvements

- src/main/java/hudson/plugins/ec2/EC2ComputerLauncher.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
- src/main/java/hudson/plugins/ec2/win/winrm/WindowsProcess.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2142 - "InterruptedException" should not be ignored
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2142
M-Ezzat
> Cleanup - squid:S2142 - InterruptedException should not be ignored

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Currently, the EBS optimized flag is ignored for spot instances.
> Ensure EBS optimized flag is passed to spot instances

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
If no custom tags were set, the slave type tag would not be set on the spot instance request.
> Ensure slave type tag is set on spot instance request

- pom.xml
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
Just need to recompile plugin against new API.
@reviewByBees
> [JENKINS-38481] 1.11.37 changed com.amazonaws.services.ec2.AmazonEC2#createTags return type, so incompatible binary change

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-deleteRootOnTermination.html
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Fixes [JENKINS-33339](https://issues.jenkins-ci.org/browse/JENKINS-33339)
> [JENKINS-33339] Allow root volumes to be deleted on termination

- src/main/java/hudson/plugins/ec2/EC2ComputerLauncher.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
NPE coming from [JENKINS-40223 ](https://issues.jenkins-ci.org/browse/JENKINS-40223) fixed
```
INFO: Connecting to ec2-xxx.eu-west-1.compute.amazonaws.com on port 22, with timeout 10000.
Dec 05, 2016 3:16:04 PM null
INFO: Failed to connect via ssh: The kexTimeout (10000 ms) expired.
Dec 05, 2016 3:16:04 PM null
INFO: Waiting for SSH to come up. Sleeping 5.
ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
java.lang.NullPointerException
at hudson.plugins.ec2.ssh.EC2UnixLauncher.bootstrap(EC2UnixLauncher.java:309)
at hudson.plugins.ec2.ssh.EC2UnixLauncher.launch(EC2UnixLauncher.java:131)
at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:122)
at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:261)
at …
```
> [FIXED JENKINS-40223] Avoid NPE when ssh connection fails and terminate agents under any Exception

- pom.xml
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
When creating on-demand instances, create tags in the same runInstances operation.
Allows to give Jenkins a restrictive IAM Role (ie. only allowed to manage instances with a given tag value) and still be able to run instances.
> Tag on-demand instances at creation using latest SDK

- src/main/java/hudson/plugins/ec2/EC2PrivateKey.java
- src/test/java/hudson/plugins/ec2/EC2PrivateKeyTest.java
[JENKINS-41824](https://issues.jenkins-ci.org/browse/JENKINS-41824) Meaningful exception message if the EC2 KeyPair private key is missing/empty:  `IOException("This private key cannot be empty")` instead of `NullPointerException()
> JENKINS-41824 Meaningful exception message if the EC2 KeyPair private key is missing/empty

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Step.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/EC2Step/config.jelly
- src/main/resources/hudson/plugins/ec2/EC2Step/help.html
- src/test/java/hudson/plugins/ec2/EC2StepTest.java
- src/test/java/hudson/plugins/ec2/util/PluginTestRule.java
Jenkins vsphere plugin allows to invoke some methods to the backend API, as noted on https://github.com/jenkinsci/vsphere-cloud-plugin/blob/master/src/main/java/org/jenkinsci/plugins/vSphereCloudLauncher.java
To enable aws provisioning (and avoid mantaining a Jenkins agent via the node step), a modification over https://wiki.jenkins-ci.org/display/JENKINS/Amazon+EC2+Plugin is needed. This could be implemented via a new pipeline step such as 
`ec2 cloud: 'AWS', template: 'aws-CentOS-7'
`
> [JENKINS-44560] Provision AWS instance from within a pipeline

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
The "minutes remaining in billing period" log entry was converting milliseconds to minutes instead of seconds to minutes.  The input was being passed in as seconds.
> update minutes remaining in billing period log entry

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
Spot instances that did not have associated instance IDs (e.g. just started or price too low) were not being counted properly. Added stricter checks to fix this behavior and still avoid double counting fulfilled requests.
Unrelated, we're still looking at the deadlock issue but it needs a bit more testing...
> Fix issue when counting non-fulfilled spot requests

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
If EC2 instance doesn't expose AMITypeData, we effectively drop the data
in the AMITypeData object. For Windows slaves this means that the
password is removed and the instance type is defaulted to unix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/ec2-plugin/243)
> JENKINS-47985: Fixing AMITypeData Storage issue

- src/main/resources/hudson/plugins/ec2/EC2Slave/help-securityGroups.html
In the security groups [parse method](https://github.com/jenkinsci/ec2-plugin/blob/master/src/main/java/hudson/plugins/ec2/SlaveTemplate.java#L291) it is using commas to delimit security group names.
> Update help-securityGroups.html security group delimiter

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Step.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/EC2StepTest.java
JENKINS-47130 EC2 plugin 1.37 fails to provision previously defined slaves
> JENKINS-50105 EC2 Step provisioning incorrectly specifies a label

- pom.xml
These dependencies are only used in tests, so they should be in test scope.
@reviewbybees
> Mark dependencies used only in tests as test scope

- src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
- src/main/java/hudson/plugins/ec2/win/winrm/WindowsProcess.java
This resolves an issue where Windows (WinRM) agent running on EC2 would intermittently fail with no apparent cause or clear way to reproduce.
This was tracked down to use of `Piped*Stream` classes that are sensitive to identity of thread used - and conflict with internal threads pooling both on client and server side.
The issue has been consistently reproducible and verified using our 30+ builds on number of dynamic ec2 instances in a row internal test harness.
**Note:** Instead of merging this, consider merging https://github.com/jenkinsci/ec2-plugin/pull/264 outright (more extensive cleanups and include this change as well).
---
Example stack trace from a failure scenario (valid use of `FilePath` resulting in attempt to make a remove call over `FilePath::act` running into a reportedly …
> Fix intermittent "Pipe closed" exception when communicating with WinRM protocol agent

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
Hello,
I've applied the following patch (similar to that in #242) to the ec2-plugin in our Jenkins installation so we can use c5 instances. I have a couple of questions though:
1. I saw that #242 failed CI, do you have some idea of whether that's a problem introduced by the version bump / something wedged on the CI environment right now / a spurious failure?
2. What are the values in `toNumExecutors` supposed to be? For the c5 instances I introduced, I've copied numbers from similar instance types (where possible) but I'm not sure I did the right thing.
Thanks in advance for your help!
Phil
> Bump aws-java-sdk to pick up c5, m5 instance types

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
On may 17th - amazon released new C5d (with local storage) instance type, bump aws-java-sdk + add new types
> Bump aws-java-sdk to pick up c5d and m5d instance types

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
Currently when jenkins is restarted, all EC2 slaves are started regardless of whether the EC2 instances are currently running.
In the case where there are a large number of slaves, this can have a non-trivial cost.
This change makes it so that when jenkins starts up, EC2 slaves are only started if the EC2 instance is running (or starting to run).
This fixes https://issues.jenkins-ci.org/browse/JENKINS-37552
> JENKINS-38311: Don't start up EC2 slaves that are turned off when Jenkins starts up

- pom.xml
[JENKINS-53285](https://issues.jenkins-ci.org/browse/JENKINS-53285)
This version is the same as 1.5, but just got a parent pom bump, and an internal change to enable findbugs checking.
Cf. https://github.com/jenkinsci/node-iterator-api-plugin/compare/7b284cb95b1ebcd09a430b94fd75d5599e867668...f73034788d1c8752ab7bef3af6aea664f3af674e for the detailed changes from 1.5 to 1.5.0
> [JENKINS-53285] bump to latest node-iterator-api

- findbugs-exclude.xml
- pom.xml
This change is to stop adding more FindBugs "violations" in other classes.
The idea is to also make fixing those more feasible progressively:
one can now remove a single "Match" entry from the exclusion file,
contribute a single fix for the related FindBugs errors, and move on.
I.e. one does not have to fix it all at once when removing "skip".
@francisu as the current maintainer.
cc @reviewbybees for more eyes.
Thanks!
> Convert global findbugs skip to specific per class

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Unfortunately, cygwin and Java are not best friends. So, JVM under cygwin is not
able to resolve '/tmp/slave.jar` properly. To avoid this issue let's
change directory first and execute local file.
After that user can use Windows node in absolutely same way as Unix node.
> Start agent in cygwin friendly way

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
`20 seconds` is too often in our case (we have a lot of nodes). So, let's users to decide the best fetch interval.
> Make fetch time configurable via system property

- src/main/java/hudson/plugins/ec2/CloudHelper.java
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Computer.java
- src/main/java/hudson/plugins/ec2/EC2ComputerLauncher.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/java/hudson/plugins/ec2/EC2Step.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/test/java/hudson/plugins/ec2/EC2StepTest.java
This commit changes the behaviour of core functionality: raising new
nodes.
It implements very simple algorithm:
- if NodeProvisioner requested X executors, start to raise
X/N nodes (N is number of executors on each node).
- if there is any orphant nodes (~not known by Jenkins at all), take
them in account (and start if it's neccessary)
- if there is not enough orphant nodes - raise needed nodes in parallel
- give them back to NodeProvisioner in RUNNING state
Also I failed to stop myself from extracting duplicated code to separate methods... sorry, for making review harder.
I attached the last version of master + this PR to this message. So, if someone wants to give a try, it's enough to download it and rename back to `.hpi` (GitHub does not allow `hpi` file extension) …
> JENKINS-25832: Launch multiple slaves in parallel

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/NoDelayProvisionerStrategy.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/help-noDelayProvisioning.html
the standard `NodeProvisioner.Strategy` has been implemented to avoid over-provisioning, mostly designed at a time EC2 instances where billed by hours, which means we didn't wanted to get an extra one while jenkins might soon have available executors.
As EC2 is now billed by the minute we can just provision a new node when we miss one without delay, in worse case it will stay for few minutes then be terminated.
> introduce a ProvisionerStrategy to provision a node without delay

- src/main/java/hudson/plugins/ec2/win/WinConnection.java
Ran into this issue when attempting to troubleshoot connection issues between master and windows slave. Instead of an ICMP packet, the "ping" method opens a TCP socket, and attempts to do an SMB file transfer.
> Improving debug messaging for WinConnector. 

- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
This change ensures that a spot instance is always terminated regardless the result of the cancellation of the spot instance request.
> Terminate spot instances properly

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
When checking caps, only count spot instance requests with tag matching our description.
> JENKINS-52012: Fix counting of slave caps with spot instances

- pom.xml
Instead of relying directly on a common dependency, this switches to the
Jenkins plugin that bundles HttpClient et al. in an easily upgradeable
Jenkins plugin. This also upgrades the base level of Java required to
1.8 as dependencies (including Jenkins) now require it.
@reviewbybees
> Upgrade baseline versions of Jenkins, Java, Apache HttpClient, and BouncyCastle

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-subnetId.html
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
[JENKINS-35708]
Allow users to supply multiple subnets for launching EC2 instances into
instead of just one. This solves the issue where you need to launch a
large amount of somewhat less available instances (e.g. GPU instances)
and need to use multiple availability zones to avoid exhausting that
instance type.
I tried to avoid breaking any backwards compatibility. I slightly
modified the behavior of the subnet ID configuration field: if you
provide a space-separated list of subnet IDs, the code will cycle
through them in order beginning with the first one. If you have one ID
it will still technically cycle through them, but the end result is that
you only launch instances into that single subnet as before, preserving
the original behavior.
I also added help text for the subnet ID field.
> [JENKINS-35708] Round-robin subnet selection

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/Eucalyptus.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
- add roleArn and roleSessionName in main config for AmazonEC2Cloud
- pass roleArn and roleSessionName in all needed methods, except for doFillRegionItems (we don't need to switch role to be able to retrieve regions)
- externalize ClientConfiguration creation to ba able to reuse it in StsClient creation (or Sts will failed in proxy environment)
- remove deprecated StaticCredentialsProvider with AWSStaticCredentialsProvider
- make createCredentialsProvider() protected and Override it in AmazonEC2Cloud
> [JENKINS-42530] Add support of switching role

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Tag.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Replaces https://github.com/jenkinsci/ec2-plugin/pull/274 (from my company)
In the case where you have multiple Jenkins masters using the same configuration (same AMI for multiple clouds), the instance cap is shared between all instances and clouds. The workaround is to add an additional tag with the Jenkins url to have this instance cap unique per Jenkins master.
> Tag slave instances to their jenkins master

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
> FIX JENKINS-54071

- pom.xml
The 1.41 introduces breaking changes from previous version, due to a new tagging schema.
> Update compatibility version

- src/main/java/hudson/plugins/ec2/ebs/ZPoolExpandNotice.java
- src/main/resources/hudson/plugins/ec2/ebs/Messages.properties
See [JENKINS-54271](https://issues.jenkins-ci.org/browse/JENKINS-54271)
The display name for the TLS configuration administrative monitor is missing. This PR tries to fix it.
@reviewbybees
@jvz as maintainer of the plugin
> Jenkins 54271

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
https://issues.jenkins-ci.org/browse/JENKINS-54266
(Also filed https://github.com/jenkinsci/instance-identity-module/pull/13 but cannot use it for now at it needs to be merged, released, and become embedded in the minimum Jenkins baseline, hence in a pretty far future.)
> [JENKINS-54266] Warn if no server URL and default to instance-identity instead

- pom.xml
This will get the [>= 3.18 parent pom](https://github.com/jenkinsci/plugin-pom/blob/master/CHANGELOG.md#318) so that the pom.xml is automatically _reincrementalified_ on normal releases and this way the EC2 plugin still gets its incremental releases published at http://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/ec2/ as expected :)
I had filed https://issues.jenkins-ci.org/browse/INFRA-1825 before realizing the issue might be on the EC2 plugin side. Hence this PR.
> Reincrementalify and update to latest parent pom

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
Also catches NPEs on startup from the node health checking thread firing
before everything's set up, which was what I saw on my production
deployment. Oddly, my staging environment was satisfied with just #318.
> JENKINS-53858: Fix NPE on startup due to uninitialized lock

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
https://issues.jenkins-ci.org/browse/JENKINS-54266
This is probably more sensible than my previous attempt on #314, and in the end matches what [@thoulen was saying would probably have been preferrable](https://github.com/jenkinsci/ec2-plugin/pull/314#issuecomment-433432132): we just do not tag in case there's no serverUrl.
It's also a followup of #310, for inter-tracking purpose.
*Anyway* the number of production instances out there without a `serverUrl` is probably close to 0, but well.
> Do not tag instances if no serverUrl

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
When using this constructor there's no way to change `deleteRootOnTermination`. No other overloaded constructors allow it, so theres no way to set it programmatically
> Use correct deleteRootOnTermination value on SlaveTemplate constructor

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-maxTotalUses.html
- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
This is a rebased and conflict-free PR based on @ariaviran's original [PR](https://github.com/jenkinsci/ec2-plugin/pull/223) to support maximum builds on slave.
This code is running in our environment for more than a year (based on ver. 1.37 of the plugin) and it's doing very good job.
> [JENKINS-8618] Support maximum builds on slave

- src/main/java/hudson/plugins/ec2/ConnectionStrategy.java
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2HostAddressProvider.java
- src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/test/java/hudson/plugins/ec2/ConnectionStrategyTest.java
- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2HostAddressProviderTest.java
- src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
This PR aims to fix the issues mentioned in: https://issues.jenkins-ci.org/browse/JENKINS-54329. Right now, the host used for connecting to the slaves is not really deterministic and restricts users as mentioned in the issue. I would like to get early feedback on this, but my plan is to also also remove the `associatePublicIp` field and use the `connectionStrategy` being used to better determine whether to associate the public IP or not. What do you guys think?
> JENKINS-54329: allow user to choose slave connection strategy.

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/SpotConfiguration.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-fallbackToOndemand.html
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Follow up to #331. When there is no spot capacity (either for spot instances with a bid price or without one), fallback to on-demand instances
> Spot instances: Fallback to on-demand when there is no capacity

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
Somewhere in the previous commits, the display name was replaced with the instance ID
This is not useful when taking a quick look at your slaves to know what you have
Especially if you have lots of Clouds
> Use a proper display name instead of the instance ID

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
```
java.lang.NullPointerException
at hudson.plugins.ec2.EC2AbstractSlave.<init>(EC2AbstractSlave.java:157)
at hudson.plugins.ec2.EC2OndemandSlave.<init>(EC2OndemandSlave.java:56)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.kohsuke.stapler.RequestImpl.invokeConstructor(RequestImpl.java:529)
at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:784)
at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.j …
```
> Fix NPE that happens on a node's modification

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
This makes sure that settings like the type (gp2/standard) are not lost
> JENKINS-51526: Clone the AMI's Root Block Device instead of making a new one from scratch

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
This change stops the plugin from launching agents if Jenkins is shutting down.
> [JENKINS-56443] Don't provision a node if Jenkins is shutting down

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
This prevents the session from sometimes being closed before the .hudson-run-init file has been written. It would also log any errors that occurred while trying.
> JENKINS-33443 Wait for touch ~/.hudson-run-init to complete

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/main/java/hudson/plugins/ec2/EC2SlaveMonitor.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/java/hudson/plugins/ec2/NoDelayProvisionerStrategy.java
- src/main/java/hudson/plugins/ec2/PluginImpl.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/UnixData.java
- src/main/java/hudson/plugins/ec2/ebs/ZPoolMonitor.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- JenkinsLocationConfiguration.get() is marked `@Nonnull` so removing null checks
- Not certain about the case in ZPoolMonitor
- Some cases seem to have null checks but will produce weird behaviour if null so likely letting `get()` throw seems reasonable
> Use non-deprecated get() and remove some unneeded null checks

- src/main/java/hudson/os/WindowsUtil.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
This PR will set by default workdir to be the `remoteFS`
> Add remoting workdir

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/SpotConfiguration.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-spotBlockReservationDurationStr.html
What it says on the tin, allows for the setting of a Spot Block when requesting a spot instance so that you get your instance for at least that duration.
https://issues.jenkins-ci.org/browse/JENKINS-46294
> JENKINS-46294: Allow block reservations for spot instances

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- Reduce the lock scope to when we need to modify the connection
- This change is aimed at reducing the time we hold the `Queue.lock` and `NodeProvisioner.provisioningLock` causing UI performance issues.
> Reduce lock hotness

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
The `EC2UnixLauncher` logs the first 160 bytes of the SSH private key to the Jenkins node log, maybe as a debugging left-over.
The SSH private key should never be exposed in logs. This pull request modifies the offending log message accordingly.
> [JENKINS-55203] Do not log private key material

- src/main/java/hudson/plugins/ec2/EC2HostAddressProvider.java
- src/main/java/hudson/plugins/ec2/util/Closeables.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/main/java/hudson/plugins/ec2/win/winrm/WindowsProcess.java
- src/test/java/hudson/plugins/ec2/EC2HostAddressProviderTest.java
The EC2 plug-in currently uses Guava Beta APIs. Using Guava's Beta APIs is [strongly discouraged](https://github.com/google/guava#important-warnings) as they can change at any time.
In fact, this issue is blocking me from finishing [JENKINS-56839](https://issues.jenkins-ci.org/browse/JENKINS-56839): Jenkins core provides Guava 11, but a test dependency I am using pulls in Guava 20. While a bit messy, this wouldn't usually be an issue due to [Guava's API stability guarantee](https://github.com/google/guava#important-warnings); however, because the EC2 plug-in is using Guava Beta APIs that work differently in Guava 20 than they did in Guava 11, my tests for [JENKINS-56839](https://issues.jenkins-ci.org/browse/JENKINS-56839) break.
I changed the following classes so that they don't rely on …
> [JENKINS-58160] Don't use Guava Beta APIs

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Before when remoteFS is blank
```
INFO: Copying remoting.jar to: /home/jenkins
Jun 25, 2019 8:26:36 PM hudson.plugins.ec2.EC2Cloud
INFO: Launching remoting agent (via Trilead SSH2 Connection):  java -Djava.io.tmpdir=/home/jenkins/tmp -jar /home/jenkins/remoting.jar -workDir 
ERROR: unexpected stream termination
java.io.EOFException: unexpected stream termination
at hudson.remoting.ChannelBuilder.negotiate(ChannelBuilder.java:411)
at hudson.remoting.ChannelBuilder.build(ChannelBuilder.java:356)
at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:431)
at hudson.plugins.ec2.ssh.EC2UnixLauncher.launchScript(EC2UnixLauncher.java:262)
at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48)
at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
at …
```
> [JENKINS-58163][JENKINS-58193] Add fallback when remoteFS is blank

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
In my logs I have lots of cases where the uptime isn't correct in the EC2RetentionStrategy checking.
This fixes the uptime value to be not stale.
* Additionally, add an early check to prevent the rest of the process if the instance is already in the target state (and remove the partial check from one code path)
> [JENKINS-57215] Fix stale uptime in EC2RetentionStrategy

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Wait for the spot slave instance to get its instanceId set before attempting to bootstrap the node
> fixing JENKINS-53952: wait for spot instances to get an instance id

- src/main/java/hudson/plugins/ec2/win/winrm/WindowsProcess.java
- When process is destroyed close all external facing streams
This is partly to defend against any weird channel issues where it still thinks the streams are alive
> Ensure external facing streams are closed

- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
- src/main/java/hudson/plugins/ec2/win/winrm/WindowsProcess.java
When using windows instances there are useless threads for `input copy: if not exist C:\Windows\Temp\ mkdir C:\Windows\Temp\` ensure that these get cleaned up also improve logging in windows
> Close stdin once shell is deleted

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/test/java/hudson/plugins/ec2/EC2StepTest.java
- Fix an issue introduced in #360 where calling `describeInstances` too often will eventually lead to locks being held for excessive time. This will cause `connect` to only check the credentials once a minute.
- #365 was attempting to mitigate this but the bottleneck changed to the `describeInstance` call
> Only check credentials once a minute

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
Hi, great plugin! It seems that when you reconfigure a node, after submitting the form the `EC2OndemandSlave` has the `templateDescription` property set to `null`. This causes a number of exceptions (on retention check, agent creation, etc.).
This PR adds an invisible field to the configuration form, to make sure `templateDescription` is preserved (just like we do with `cloudName`).
It also renames constructor parameter name to `templateDescription`, so that it matches the field name and can be bound.
> Make sure templateDescription is preserved when reconfiguring a node

- pom.xml
- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/Eucalyptus.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/util/AmazonEC2Factory.java
- src/main/java/hudson/plugins/ec2/util/AmazonEC2FactoryImpl.java
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2StepTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
- src/test/java/hudson/plugins/ec2/util/AmazonEC2FactoryExtensionFilter.java
- src/test/java/hudson/plugins/ec2/util/AmazonEC2FactoryMockImpl.java
@jvz Please checkout this review, as per our discussion in #343 
I've broken out the EC2Cloud.connect() method to a factory that's injected with Guice and created a custom Guice module for binding that factory. That way, the actual implementation is overridable using a System property and tests can use a factory that mocks AmazonEC2.
I also refactored a bit of the existing production code and tests, getting rid of the isTestMode() in AmazonEC2Cloud and reduced the visibility of a few fields that were accessed directly from tests.
> Remove test code in production code

- pom.xml
Seems like this still works but we should use the new version to prevent forward compat issues
> Bump JCasC version to test against security advisory

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
JENKINS-58578 Force the setting of the private ip also for public subnet
> [JENKINS-58578] Force the setting of the private ip also for public subnet

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
[JENKINS-59459](https://issues.jenkins-ci.org/browse/JENKINS-59459)
Revert both fields from being transient so that they are exported and thus older version of the plugins are still able to import the template.
@dgarzon
> [JENKINS-59459] Revert both fields from being transient

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
I realized that 0 was not a valid number for minimum number of instances after I tried out the new release.
Only a form validation error, so it's still possible to continue despite having 0 as the value, but this fixes that issue.
> Allow 0 in form validation for minimum number of instances

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
If you specify network interfaces you must not specify the subnet or security groups on the instance level.
Essentially what happens is when you specify a network interface all networking related configurations must be on the interface specification or the ec2 api will return an error.
> [JENKINS-59562] Always use network interface for subnet

- pom.xml
Bump to latest pom and aws-sdk.
Latest aws-sdk has support for new GPU g4 instances.
> Bump aws-sdk and pom

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2PrivateKey.java
- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/main/java/hudson/plugins/ec2/EC2Step.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/ssh/HostKeyVerifierImpl.java
- src/main/java/hudson/plugins/ec2/win/WinConnection.java
- src/main/java/hudson/plugins/ec2/win/winrm/NegotiateNTLMSchemaFactory.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
- src/test/java/hudson/plugins/ec2/EC2StepTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
- src/test/java/hudson/plugins/ec2/ssh/HostKeyVerifierImplTest.java
Removing all the deprecated code particularly in the WinRM bits
> Use non-deprecated code and remove unused imports

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- Get the API to do the filtering instead of doing it ourselves
> Use filter query when describing instances

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
Root Cause Analysis:
The use of threadpool at times causes some threads to return old values of instance state when making the getState() call. I was able to replicate similar thing using a ruby script (preferred language) that started a stopped instance and used about 10 threads to poll the state method, few threads still returned stopped for a millisecond interval although the instance had already moved to pending. This causes some instances to be started on AWS but are never connected and also, never stopped/terminated
Solution:
1. Add a retry logic on receiving `stopped`  state from the `getstate()` method. The thread will wait for 5 seconds before retrying.  I have been testing this fix in our internal environment and a retry attempt of 1 seems to work perfectly. The retry count can …
> [JENKINS-57795] Retry when waking up orphans or creating new nodes 

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
Proposal to allow defining node properties (environment variables, tool locations, etc.) that will be applied to created slaves.
`EC2AbstractSlave` and children already take a `nodeProperties` parameter, so we just need to add the field to `SlaveTemplate`.
> Allow defining node properties on template

- src/main/resources/hudson/plugins/ec2/EC2Slave/help-stopOnTerminate.html
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-stopOnTerminate.html
~Remove obsolete help text for help-stopOnTerminate.html. EC2 is now billed per second (min 60 seconds), so short stop timeouts are no longer counterproductive.~
Add clarification that short stop timeouts only matter for windows agents.
> Update EC2Slave and SlaveTemplate help text

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
- src/main/java/hudson/plugins/ec2/util/MinimumNumberOfInstancesTimeRangeConfig.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-minimumNumberOfInstancesTimeRangeConfig.html
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Follow-up to PR #401, this PR adds the option to limit minimum number of instances to a specific time range.
I got some wishes for that from work so that we don't have build agents up and running all weekend when no one is working.
> Support limiting minimum instances to a time range

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
We have a problem where the environment in which we run Jenkins isn't allowed to talk to HTTP endpoints, only HTTPS, which means the region picker doesn't work unless we supply the alternative EC2 endpoint URL. This gets around the problem but any time someone saves the Jenkins config and forgets to put the alternative endpoint URL in (even when changing unrelated config) it fails to get the region list and therefore saves an empty region into the config which causes issues when trying to spin up EC2 instances using the plugin.
The quickest, easiest solution I could come up with is to change the default endpoint to use HTTPS instead of HTTP—this should benefit everyone by protecting against e.g. MITM attacks whilst also solving our issue. The other solution would be to store the …
> Make the default EC2 endpoint use HTTPS

- README.md
- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/Eucalyptus.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/EC2Cloud/help-privateKey.html
- src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly
See [JENKINS-51316](https://issues.jenkins-ci.org/browse/JENKINS-51316) for the reasons behind this change.
> [JENKINS-51316] Remove generateKey functionality

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-minimumNumberOfSpareInstances.html
- src/test/java/hudson/plugins/ec2/EC2SlaveMonitorTest.java
- src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
Currently there is a parameter for minimum number of instances for an AMI,
if you set it to n, there will always be at least n instances.
This PR adds minimum spare instances, if you set this to n, there will
always be n unsused instances waiting for new builds (unless the
instance cap is reached). This prevents new builds from having to wait
for provisioning, while also meaning that you don't need to set a high
absolute minimum.
Related: conjurinc/ops#401
> Add Per-AMI Spare Instance parameter

- pom.xml
Exclude the other bouncy castle version that gets pulled in as a transitive dependency from smbj.
Multiple versions can cause problems. Without excluding it
there can be test failures with bouncycastle-api 2.18
(bouncy castle 1.64).
Also update to latest bouncy castle.
> Exclude other bouncy castle version

- pom.xml
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Computer.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/win/EC2WindowsLauncher.java
Recently we encoutered an issue where when a SlaveTemplate is removed but an old Instance that uses this slave template still exists it will throw an NPE.
This PR annotates the methods and reworks the code to handle such scenarios more gracefully.
> Handle cases where SlaveTemplate has been removed

- src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
Since https://javadoc.jenkins-ci.org/hudson/model/Queue.Item.html#getAssignedLabel-- can return
null, it is unsafe to call 'label.matches(...)'. Removing all null elements from the stream
before the unsafe call prevents the NPE reported in https://issues.jenkins-ci.org/browse/JENKINS-61146
> Added null-check in MinimumInstanceChecker

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
This is a follow-up fix for PR #382.
In 2.204, the "Configure Clouds" screen was on the main /configure system
configuration page. As a result, `${it}` referred to the global system
object, aka the Hudson instance.
In 2.205, PR jenkinsci/jenkins#4339 merged, which moves the Configure Clouds
section to a new page: /configureClouds. As a result of that change, `${it}`
no longer refers to the Hudson instance, but to a new
GlobalCloudConfiguration object. That object does not have the
`getNodePropertyDescriptors()` method, so it is not able to populate the
"Node Properties" block.
Switching that to `${app}` gives it a correct reference to the Hudson object,
and that allows it to show the Node Properties block on all Jenkins versions,
both before and after v2.205.
> [JENKINS-36544] Fix Node Properties on Jenkins 2.205+

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/java/hudson/plugins/ec2/util/ResettableCountDownLatch.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
Offload termination of agents so as to not stall `NodeProvisioner.update` when NodeProvisioner.update is called it will hold the queue lock. In order to reduce the hotness of this lock schedule all terminates to be off thread
> Offload terminates to separate thread

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
I upgraded the EC2 plugin to the latest available version (`ec2-1.49.1`) and found that our cloud was spinning up workers with `null` public DNS hostnames:
An agent trying to connect would show these logs:
> Connecting to null on port 22, with timeout 10000.
Additionally, I observed in the EC2 UI that this new instance's public DNS ip address was blank (`i-003...` corresponds to `ec2-1.49.1`; `i-00f...` corresponds to `ec2-1.45`).
The underlying AWS VPC, subnet, and security groups were left unchanged between the plugin versions. Our EC2 cloud template is configured (and also unchanged) with the "Public DNS" connection strategy and "Associate Public IP" set to `false`.
Under `ec2-1.49.1`, the necessary AWS network configuration needed to provision a new EC2 instance is only set on the …
> Conditionally set AWS network configuration directly on EC2 request if associate public ip is true

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
- src/test/java/hudson/plugins/ec2/util/AmazonEC2FactoryMockImpl.java
The spot API is unbounded if MaxResults is not specified which can cause long waits and possible connection timeouts if an account has a lot of spot instances. This commit specifies the MaxResults parameter to the spot-describe-instances-request API to trigger the pagination response and wraps the code in a pagination do-while loop. 
I tested this on a clean jenkins install with 105 spot instances. The response properly paged through the additional 5 instances in the second page of results.
> Use Spot Pagination API

- spotbugs-exclude.xml
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
In PR #433, which was released in AWS EC2 Plugin 1.50, a bug was introduced due to improper
handling of an important transient field which is accessed very frequently by the Jenkins server
due to it being referenced in `EC2AbstractSlave.isAcceptingTasks()`. This broke any Jenkins
user which had running EC2 Nodes during the update to plugin 1.50 (see
https://issues.jenkins-ci.org/browse/JENKINS-62043 for details).
> [JENKINS-62043] Fix NPE which broke Jenkins builds

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
https://github.com/jenkinsci/ec2-plugin/pull/449 contained a bug where a DescribeInstances filter "instance-state-name" was propagated to the DescribeSpotInstanceRequests API call and is unsupported within that call.  I was able to reproduce the bug on the 1.50 release and tested that it is working properly with this patch.
> FIX: Bad filter passed to DescribeSpotInstanceRequests API

- pom.xml
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
- src/test/java/hudson/plugins/ec2/EC2HostAddressProviderTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
WIP to fix the build on ci.jenkins.io
> Fix CI Errors

- src/main/java/hudson/plugins/ec2/HostKeyVerificationStrategyEnum.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-hostKeyVerificationStrategy.html
This plugin was upgraded on our Jenkins server, and we were unaware of the host key requirement changes (and our AMIs are incompatible without some extra effort).  We were unable to continue without downgrading, because the SSH syntax for the "off" option is incorrect, leading to the following error, even when the "Host Key Verification Strategy" was set to off:
```
$ ssh -o StrictHostKeyChecking=off -i /var/lib/jenkins/tmp/ec2_4085601235825214564.pem jenkins@172.33.200.99 -p 22  java -Dfile.encoding=UTF8 -jar /tmp/remoting.jar -workDir /jenkins
command-line line 0: unsupported option "off".
```
It should be `-o StrictHostKeyChecking=no`
(we have every intention of fixing the AMIs, and the new feature makes sense, but we like to keep our Jenkins plugins relatively up-to-date, and breaking …
> StrictHostKeyChecking=off should be StrictHostKeyChecking=no

- src/main/java/hudson/plugins/ec2/CloudHelper.java
See [JENKINS-62227](https://issues.jenkins-ci.org/browse/JENKINS-62227)
Sometimes Jenkins fails to start, it gets hung with:
```
2020-05-09 12:19:27.321+0000 [id=46]    SEVERE  hudson.triggers.SafeTimerTask#run: Timer task hudson.slaves.ComputerRetentionWork@5988e277 failed
java.lang.NoClassDefFoundError: Could not initialize class hudson.plugins.ec2.CloudHelper
at hudson.plugins.ec2.EC2Computer.getState(EC2Computer.java:139)
at hudson.plugins.ec2.EC2RetentionStrategy.internalCheck(EC2RetentionStrategy.java:146)
at hudson.plugins.ec2.EC2RetentionStrategy.check(EC2RetentionStrategy.java:107)
at hudson.plugins.ec2.EC2RetentionStrategy.check(EC2RetentionStrategy.java:52)
at hudson.slaves.ComputerRetentionWork$1.run(ComputerRetentionWork.java:70)
at …
```
> [JENKINS-62227] Replace slf4j by java logging in CloudHelper

- README.md
See [JENKINS-62231](https://issues.jenkins-ci.org/browse/JENKINS-62231)
I've created this PR to warn users about the problem downgrading from any of the security releases. The issue triggers you loose your cloud configuration. 
The workaround is to remove the ec2.xml file before restarting Jenkins. This file is created if you click on the button _Dismiss these messages_ of the new AdministrativeMonitor which warns you when you have templates with a weak template. If you don't do that, there isn't any issue.
I was pondering to put this kind of warning in the `index.jelly` file, to have it very visible when you see the update on the pluginManager. Because here, is very late IMO.
> [JENKINS-62231] Warn about downgrade issue

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Signed-off-by: Raihaan Shouhell <raihaan.shouhell@autodesk.com>
Specify setting on only 1 part of the request amends #447 
CC: @jzyeezy
> [JENKINS-62090] Specify SGs only on 1 part of request

- README.md
Here is a fix for the example "Configure plugin via Groovy script".
Error # 1:
> groovy.lang.GroovyRuntimeException: Could not find matching constructor for: hudson.plugins.ec2.UnixData(null, null, null)
Error # 2:
> groovy.lang.GroovyRuntimeException: Could not find matching constructor for: hudson.plugins.ec2.AmazonEC2Cloud(java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.util.ArrayList)
P.S.: I don't know Java, so please check syntax and logic, maybe I did wrong fix. But Jenkins script console works fine with this fix.
> README: Groovy script: fix UnixData and AmazonEC2Cloud

- src/main/java/hudson/plugins/ec2/ssh/verifiers/SshHostKeyVerificationStrategy.java
Fix an issue retrieving the host key from the instance console.
See [JENKINS-62221](https://issues.jenkins-ci.org/browse/JENKINS-62221)
> [JENKINS-62221] Bug fix parsing the line with the host key in the console

- pom.xml
When I upgraded to 1.50.3 (from an ancient version which was no longer compatible with modern Jenkins), connections to Windows nodes started failing with no errors in any logs, which I traced to a NoClassDefFoundError caused by loading SLF4J classes from both the plugin and Jenkins itself. The lack of logging remains, but excluding SLF4J from the SMBJ dependency fixes the problem for me. I have no idea if this is the right solution, though.
This may be what's causing https://issues.jenkins-ci.org/browse/JENKINS-62641.
> Exclude SLF4J from smbj since it causes class loading errors.

- pom.xml
Picks up https://github.com/jenkinsci/aws-java-sdk-plugin/releases/tag/aws-java-sdk-1.11.821
> [JENKINS-62489] Support m6g ec2 instances

- src/main/java/hudson/plugins/ec2/WindowsData.java
Move if block before assignation to set correctly the property
> fix backward compatibility  for windows data

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
- src/test/java/hudson/plugins/ec2/EC2SlaveMonitorTest.java
- src/test/java/hudson/plugins/ec2/util/SSHCredentialHelper.java
I changed the behavior from my feature added in #445 as suggested by @daniel-beck by moving the migration code to EC2Cloud.readResolve(). I also tested again the migration from 1.51 to 1.52. I could confirm that it wasn't working before and that it works now for me with that change.
Not sure why the @RequirePost lead to issues as it was requested as an addition but maybe someone can clarify if there is a better way than just removing it for now.
Thanks to @varyvol for the bugnotice and @daniel-beck for the hint how to fix it quickly.
> Bugfix: Removed @RequirePost and changed ssh key migration behavior

- src/test/java/hudson/plugins/ec2/EC2CloudMigrationTest.java
- src/test/resources/hudson/plugins/ec2/EC2CloudMigrationTest/testPrivateKeyMigrationToSshCredentials/config.xml
Adds to #498 an automated test validating the migration for an EC2 cloud is correctly done.
@MRamonLeon @djesionek
> Test to validate the EC2Cloud private key migration 

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
It appears the response from this request is discarded, and the request
is made only to validate we still have a good connection to AWS.
This prevents the connection polling from returning _all_ ec2 instances
in the AWS account, using up AWS API quotas (which take result size into
account for API quota tracking purposes).
We are running a semi-degenerate setup with ~50 instances in a single AWS account, all of which make this unfiltered request every minute, and have been getting API throttled.  My rough understanding is that this is just a health check and we don't actually need the whole query result, and we've been running one master with this patch with no ill effects so far, but it's entirely possible I'm misinterpreting the purpose of this request.
> JENKINS-62212 Add filter to periodic EC2 connection polling

- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiType.html
Referring to the documentation from the Cloudbees side: https://support.cloudbees.com/hc/en-us/articles/216091837-EC2-Plugin-Out-of-Memory-issue-when-launching-agents-in-AWS?mobile_site=false 
In our case we had a similar problem, MSBuild could not build large projects, change this parameter resolved the problem on our side.
> Change parameter for MaxMemoryPerShellMB to 10GB 

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
- src/test/java/hudson/plugins/ec2/util/TestSSHUserPrivateKey.java
Use the general `SSHUserPrivateKey` type when looking up SSH credentials instead of the `BasicSSHUserPrivateKey` concrete subtype. This will allow the plugin to use any compatible SSH key, not just `BasicSSHUserPrivateKey` instances.
Fixes [JENKINS-63986](https://issues.jenkins-ci.org/browse/JENKINS-63986)
> Use SSHUserPrivateKey instead of BasicSSHUserPrivateKey

- src/main/resources/hudson/plugins/ec2/EC2Tag/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/lib/ec2/blockWrapper.jelly
Still broken on < 2.264 but seems to work on the newest versions.
Not sure what the issue is, any idea @timja
> [JENKINS-64147] Forwards compat with table-to-div

- src/main/java/hudson/plugins/ec2/EC2Filter.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/EC2Filter/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-ami.html
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiFilters.html
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiOwners.html
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-amiUsers.html
- src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
- src/test/java/hudson/plugins/ec2/EC2FilterTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
- src/test/resources/hudson/plugins/ec2/Ami.yml
Allow finding the image to launch by the various `describeImages` criteria instead of just a specific image ID. Currently you're required to reconfigure the plugin whenever the image is updated, which is inconvenient.
Fixes: https://issues.jenkins.io/browse/JENKINS-59180
> [JENKINS-59180] Allow AMI filtering instead of AMI ID

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
- src/test/resources/hudson/plugins/ec2/UnixData-withAltEndpoint.yml
- src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpoint.yml
See https://issues.jenkins-ci.org/browse/JENKINS-60482
Simplified version of https://github.com/jenkinsci/ec2-plugin/pull/439
Reasoning:
The field `Alternate EC2 endpoint` has only one purpose, to fill up the `Region` field. If you're in an environment where the default endpoint is not reachable, you can specify here the full url to use instead. Like: `https://ec2.us-west-1.amazonaws.com`. Once the field is populated, the connection and all other operations are performed using this region, so they should go fine.
It's true that every time you enter the configuration page, the `Alternate EC2 endpoint` is empty, so the `Region` field never gets populated until you set the endpoint properly. So it causes a lot of frustration and misunderstanding, IMO.
This PR tries to resolve the problem by …
> [JENKINS-60482] Persist the alternate ec2 endpoint

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/resources/hudson/plugins/ec2/Messages.properties
Follow up on #537 (JENKINS-60482) to better manage errors when setting the **_Alternate EC2 endpoint_**.
If the URL is wrong, you get an angry Jenkins on the field row:
With this PR it's not displayed and you get an error message behind the field:
Log:
```
2020-11-24 15:38:10.712+0000 [id=81]    WARNING h.p.e.AmazonEC2Cloud$DescriptorImpl#determineEC2EndpointURL: The alternate EC2 endpoint is malformed (https.//ec2.us-east-1.amazonaws.com). Using the default endpoint (https://ec2.amazonaws.com)
```
Once you fix the wrong URL (In the image by removing the `https.` by `https:`), it works:
> [JENKINS-60482] Improve alternate ec2 point checks

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
See https://issues.jenkins.io/browse/JENKINS-61161
Avoid the ugly and erroneous _Could not find selected connection strategy_ every time one changes the connection strategy.
See:
> [JENKINS-61161] Avoid infamous UI connection strategy warning

- src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
The inspiration came from https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/lib/form/dropdownListBlock.jelly#L38.
The problem was the row just to have a hidden input to specify the `stapler-class`, when in fact the `dropdownListBlock` has an attribute to store this value.
> [JENKINS-62908] Remove table row for embedded descriptor class

- pom.xml
PCT is failing on ConfigurationAsCodeTest#testConfigAsCodeExport and ConfigurationAsCodeTest#testConfigAsCodeWithAltEncpointExport because it needs an updated JCasC.
This PR bump the bom to catch the CasC needed.
> [JENKINS-60482] Update bom to fix PCT failures because of JCasC outdated

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
When a new node is provisioned from EC2, the instance data should be
lazily fetched in order to avoid generating network traffic in the
NodeProvisioner thread. All the getters for the attributes updated by
fetchLiveInstanceData call it first to update if need be, so there's no
need to be eager here.
> Don't fetch instance data on node creation

- src/main/java/hudson/plugins/ec2/CloudHelper.java
- src/test/java/hudson/plugins/ec2/CloudHelperTest.java
On a private jenkins server we were experiencing a problem where the EC2SlaveMonitor would query aws for an agent and get a response code with the error code 'RequestExpired'. This would result in the slave monitor deleting the agents from jenkins but the instances were still running within aws. Worse the orphaned agents would still count towards the instance cap and eventually prevent us from spinning up additional agents when required.
Adding the timeout condition to the retry logic resolved this problem for us.
> Add retry logic for connection timeout exception

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
- src/main/java/hudson/plugins/ec2/util/MinimumNumberOfInstancesTimeRangeConfig.java
- src/main/resources/hudson/plugins/ec2/EC2Cloud/help-sshKeysCredentialsId.html
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/resources/hudson/plugins/ec2/Unix-withMinimumInstancesTimeRange.yml
Instead of a map which is not supported by JCasC, use individual fields. This
requires a readResolve to convert the old objects to the new format.
This PR also fixes up some of the layout for these buttons, and adds back a missing help test for the sshKeys.
> [JENKINS-60647] Fix JCasC for minimumNumberOfInstancesTimeRangeConfig

- src/main/java/hudson/plugins/ec2/EbsEncryptRootVolume.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-ebsEncryptRootVolume.html
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
- src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpoint.yml
- src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
**What does PR do:**
This PR implements option to encrypt root EBS volume from unencrypted AMI
**Why:**
Our security policy requires EBS volumes to be encrypted, and since all public AMIs need to be unencrypted, in order for us to use them we would require this implementation.
Since 2019 it is possible to encrypt EBS backed EC2 instances from unencrypted AMIs; more about  it [here](https://aws.amazon.com/about-aws/whats-new/2019/05/launch-encrypted-ebs-backed-ec2-instances-from-unencrypted-amis-in-a-single-step/).
> Option to launch encrypted EBS root volume from unencrypted AMI

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Pass ssh host key to ssh process when using the strategy CHECK_NEW_HARD. Without this when connecting via ssh process, the ssh process might not have the ssh host key. Take the ssh host key that jenkins already verified and pass that to the ssh process.
> [JENKINS-64520][JENKINS-62340] Pass ssh host key to ssh process when using the strategy CHECK_NEW_HARD

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
- src/main/java/hudson/plugins/ec2/win/winrm/request/ExecuteCommandRequest.java
- src/main/java/hudson/plugins/ec2/win/winrm/request/OpenShellRequest.java
- src/main/java/hudson/plugins/ec2/win/winrm/soap/Header.java
- src/main/java/hudson/plugins/ec2/win/winrm/soap/HeaderBuilder.java
- src/main/java/hudson/plugins/ec2/win/winrm/soap/Namespaces.java
To secure a future upgrade in core.
> Removed usage of Guava

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/Eucalyptus.java
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
Proposing this as this is useful in CloudBees products where Cloud implementation can be configured within Folders within folders, then pushed connected Jenkins instance. Similar feature were added to for example the kubernetes plugin: https://github.com/jenkinsci/kubernetes-plugin/commit/00ca6a819d951ebf481b21be6750493594a9b8ce
I have added a test to validate that this does not impact the current functionalities.
> Fill credentials from current context instead of just Jenkins singleton

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Description of the issue available at: https://issues.jenkins.io/browse/JENKINS-64571
> [JENKINS-64571] Fall back to on demand provisioning when spot quota exceeded and option set

- pom.xml
- src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
Update minimum core version and bom
Since https://github.com/jenkinsci/jenkins/pull/5047 was merged in Jenkins Core, the library `libzfs` was removed. This library is required in this plugin but was not properly described.
> Add required library to project configuration

- src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
Turns out the typo fixed in [608](https://github.com/jenkinsci/ec2-plugin/pull/608) wasn't the only thing wrong. The `instance` var is only reassigned inside the `dropdownListBlock` element, so `instance.amiType` should be used in the `staplerClass` attribute instead.
The fix has been tested manually and now works as expected.
> [JENKINS-64738] Fixed reference to get the amiType class name

- pom.xml
Removes the pinned version of script-security plugin now that the BOM has the correct minimum version required to have the caffeine-api plugin.
Replaces #618.
@MRamonLeon
> Script security version fix

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
Changes the behaviour when the AMI ID and search are blank from logging a warning to raising an exception. Motivated by experiencing what happens when it just warns:
We use the configuration-as-code plugin; when interpolating secrets, if you have a typo in the secret name, it inserts the empty string:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/e7501727c4704aaa1e95bdc246a1454dc5b20440/plugin/src/main/java/io/jenkins/plugins/casc/SecretSourceResolver.java#L124
Unfortunately we had a typo in the name of an AMI used by a rarely-run job, which used a slightly different AMI from all the other jobs on our server. So, when we deployed, we missed the warning message:
Configuration import: Found unresolved variable '/plugins/amazonEC2/special-ami'. Will default to empty string …
> Raise an exception when AMI search is blank.

- src/main/java/hudson/plugins/ec2/ConnectionStrategy.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
The issue seems stem from `ConnectionStrategy` having both a name field and function which seems to cause confusion so doFillConnectionStrategy can be called with either displayText or the enum NAME we only want the name but displayText was stored in the name field. Rename to prevent this issue
> Fix connection strategy UI prompt

- src/main/java/hudson/plugins/ec2/util/DeviceMappingParser.java
- src/test/java/hudson/plugins/ec2/util/DeviceMappingParserTest.java
Closes https://issues.jenkins.io/browse/JENKINS-64569 by adding the `throughput` param to the end of the parser for the colon separated string. Based on other existing tests which have fewer separators than options, this should be entirely backwards compatible with existing block device config strings.
I've written a simple test, but I'm having issues getting the `util` tests to run both locally and in CI. It seems like maybe they aren't getting picked up by the Maven project?
> [JENKINS-64569] Add support for EBS Throughput parameter

- src/main/java/hudson/plugins/ec2/EC2Computer.java
- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
when a node just booted it is not connected, and simultaneously its idle start time could still be set to the previous time the node was booted. If the instance is checked by the plugin while in this phase, the plugin will erroneously decide to terminate it again. The change in this PR adds a safety check to ensure that idle time is calculated from the greatest of idle time as returned by jenkins or the node uptime, as returned by EC2.
Fixes: https://issues.jenkins.io/browse/JENKINS-23792
> [JENKINS-23792] Do not terminate stopped EC2 nodes that were just booted

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-subnetId.html
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
It looks reasonable to use more symbols to divide VPC subnets in Jenkins agent configuration. It can be used when you want to configure EC2 plugin through CASC (configuration-as-a-code) and perform evaluation some values from AWS SSM Parameter Store. In this case list of VPC subnets is provided as a comma separated values in a string.
I've added a regular expression that includes new symbols to split string of VPC subnet ids into array of its values.
> Adds new delimeters for subnet configuration: white spaces, comma, semicolon can be used

- src/main/java/hudson/plugins/ec2/win/winrm/WinRM.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRMClient.java
- src/main/java/hudson/plugins/ec2/win/winrm/WinRMConnectionManagerFactory.java
> win: cleanup some windows warnings and deprecated code

- src/main/java/hudson/plugins/ec2/AMITypeData.java
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/UnixData.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/resources/hudson/plugins/ec2/UnixData/config.jelly
- src/main/resources/hudson/plugins/ec2/UnixData/help-bootDelay.html
- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Our EC2 Windows slaves were suffering from frequent disconnects, causing any in-progress builds to fail.  Knowing that our Linux slaves were far more stable, we decided to experiment with SSH connections for Windows.
Using a customized daemon (https://github.com/varju/ec2-sshd), we have found that our Windows slaves are now consistently staying connected.  Unfortunately sshd on Windows suffers from the same problem as WinRM, requiring a bit of a delay after startup due to services that restart shortly after boot.
This PR adds a boot delay option to Unix slaves.  Normally the delay will be 0, but this can be manually increased if using a less conventional setup like Windows over SSH.
> Add optional bootDelay parameter for SSH slaves

- README.md
A new feature was added version 1.68 to allow for a boot delay for SSH
workers. This in turn created a breaking change in the UnixData
constructor. Updated README to follow new constructor.
New Feature PR: https://github.com/jenkinsci/ec2-plugin/pull/716
Commit change: https://github.com/jenkinsci/ec2-plugin/blob/a8abc59dd6b7c54f2c4e10ff754cf411d06bcdfc/src/main/java/hudson/plugins/ec2/UnixData.java#L24
Excerpt:
```
@DataBoundConstructor
public UnixData(String rootCommandPrefix, String slaveCommandPrefix, String slaveCommandSuffix, String sshPort, String bootDelay) {
this.rootCommandPrefix = rootCommandPrefix;
this.slaveCommandPrefix = slaveCommandPrefix;
this.slaveCommandSuffix = slaveCommandSuffix;
this.sshPort = sshPort;
this.bootDelay = bootDelay;
this.readResolve();
}
```
> Update README to use proper constructor for UnixData

- src/main/java/hudson/plugins/ec2/CloudHelper.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2SlaveMonitor.java
[JENKINS-63537](https://issues.jenkins-ci.org/browse/JENKINS-63537) - EC2SlaveMonitor terminates agent with a running job when STS session expires
* Add conditional logic to skip removal of nodes when RequestExpiredPredicate.test(AmazonClientException) returns true
This pull request is an alternative implementation to #493 as proposed @MRamonLeon. I am working on including tests for the new functionality.
> Detect an expired request exception

- .mvn/extensions.xml
- pom.xml
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudUnitTest.java
- src/test/java/hudson/plugins/ec2/CloudHelperTest.java
- src/test/java/hudson/plugins/ec2/EC2CloudTest.java
- src/test/java/hudson/plugins/ec2/EC2StepTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateUnitTest.java
Without this PR, running the test suite with `jenkins.version` set to the latest weekly fails with:
```
java.lang.IllegalArgumentException: org.kohsuke.stapler.ClassLoaderValue$X referenced from a method is not visible from class loader
at java.base/java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Proxy.java:858)
at java.base/java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Proxy.java:681)
at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:627)
at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:635)
at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:415)
at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
at …
```
> Remove PowerMock

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
In our current environment we have agents that are launched by the ec2-plugin that build individual Ivy/Maven Module builds. These module builds must build on the same node as their parent.
In the event that their parent node is terminated then the module can no longer be built.
To solve this in our environment we have made a small change to the EC2RetentionStrategy class that will check for items in the queue just prior to termination.
We have been using this change on multiple versions of the ec2-plugin for the last 6 years.
This pull requests includes changes to the EC2RetentionStrategy that prior to a nodes timout checks if there are any builds in the nodes queue. If there are builds in the queue it prevents the node from timing out. …
> [JENKINS-69399] Prevent offlining ec2 node if jobs in node queue

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/resources/hudson/plugins/ec2/MacDataExport.yml
- src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpointAndJavaPath.yml
- src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
This PR properly builds upon part of the aim of https://github.com/jenkinsci/ec2-plugin/pull/748. I had had an issue (my issue, unrelated to the plugin) locally building and installing the plugin to test that the default value of `metadataTokensRequired` was set to true by default. After the release of `2.x.x` of the plugin was released, I upgraded the EC2 plugin on my own Jenkins controller and saw that value of still false by default.
_This screencast shows the current behavior, using ec2 plugin 2.0.2_
https://user-images.githubusercontent.com/18095335/189275546-3d3895d2-ffdd-47af-b773-3377aeec49bf.mov
- As a result, I'm creating this follow up PR, which I have been able to successfully build, install on a Jenkins controller, and verify that `metadataTokensRequired` is checked by …
> Ensure that IMDSv2 Configuration Option is set to `true` by default

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Computer.java
- src/main/java/hudson/plugins/ec2/EC2Step.java
- src/main/java/hudson/plugins/ec2/MacData.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/UnixData.java
> add post annotations and permissions checks

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
Currently, in the configuration page for a node it incorrectly always displays the default values for these 3 fields, which can be really confusing.  Getters are required so that these private fields appear correctly in this template https://github.com/jenkinsci/ec2-plugin/blob/master/src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly#L142.
> Add getters for IMDSv2 metadata fields

- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
If Jenkins recieves a non-zero error code when runing `java -fullversion` on the remote agent then it will install java 11 using yum.
Previously this installed java 8 which is no longer supported on Jenkins agents where the controller is running version 2.361.x or higher.
This issue is discussed further in [JENKINS-69581](https://issues.jenkins.io/browse/JENKINS-69581)
> JENKINS-69581: Install java-11-openjdk

- src/main/resources/hudson/plugins/ec2/EC2Cloud/computerSet.jelly
Follow up of https://github.com/jenkinsci/jenkins/pull/7573.
This has no effect on older versions of Jenkins. On newer versions of Jenkins this prevents a bug that I've briefly described in the PR linked above.
> Use `Cloud#getUrl` in /provision URL

- src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
To install the java to mac2.metal instance type , we will need to install the rosetta terminal so that the java can be install once the system is booted up.
We added the condition where if the current computer instance type is mac2.metal then only install the rosetta terminal.
> Adding rosetta terminal support for mac2.metal instance type

- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/test/java/hudson/plugins/ec2/ConfigurationAsCodeTest.java
- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
This makes the plugin compatible with cloud copy feature that is being introduced in Jenkins core, cf. https://github.com/jenkinsci/jenkins/pull/7658
> Remove cloudId and use the name entered by the user directly.

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/Eucalyptus.java
- src/main/resources/hudson/plugins/ec2/Eucalyptus/config-entries.jelly
- src/test/java/hudson/plugins/ec2/EucalyptusTest.java
Context: https://github.com/jenkinsci/jenkins/pull/7658 is adding support for copying clouds. Clouds defining a fixed name should now support a name provided by the user.
> Adds support for custom name for Eucalyptus. Also fixes roundtrip for ec2Endpoint and s3Endpoint

- README.md
- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/util/EC2AgentConfig.java
- src/main/java/hudson/plugins/ec2/util/EC2AgentFactoryImpl.java
- src/main/resources/hudson/plugins/ec2/EC2Computer/configure.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-metadataSupported.html
- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/java/hudson/plugins/ec2/util/EC2AgentFactoryMockImpl.java
- src/test/resources/hudson/plugins/ec2/MacDataExport.yml
- src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpointAndJavaPath.yml
- src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
After https://issues.jenkins.io/browse/JENKINS-65127 was introduced with https://github.com/jenkinsci/ec2-plugin/pull/609, AMIs without Instance Metadata support were broken. When they were provisioned, they wouldn't get key pairs properly installed by AWS EC2 (the init script on the AMIs would get stuck on waiting to access instance-metadata).
This change introduces a new option to indicate if an AMI does not support instance metadata and thus no `InstanceMetadataOptionsRequest` will be included in the EC2 request to provision an instance. 
- Introduced a new automated test SlaveTemplateTest.provisionOnDemandWithUnsupportedInstanceMetadata()
- Ran `mvn test` to make sure no other tests were broken.
- Ran `mvn hpi:run` to make sure the UI showed the new option for metadata supported. …
> JENKINS-71655: Add support for AMIs without instance metadata support

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
`EC2AbstractSlave` overrides `readResolve` method but does not call super method. This means object initialization may be incomplete after coming back from a restart.
```[tasklist]
```
> Call super method in `EC2AbstractSlave#readResolve()`

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/test/java/hudson/plugins/ec2/EC2CloudTest.java
**PR Description:**
+ Added a method which would access the templates SlaveTemplate list and add a new one if a template with the same description doesn't already exist.
+ Added Unit test to verify that the new  SlaveTemplate has been added successfully 
**Use Case:**
We have a few packer jobs that create new slave template agents  on demand, the issue with the current state of the ec2-plugin (prior to the changes) is that whenever we run a packer job someone will have to go and manually add the new SlaveTemplete to the EC2Cloud. 
I found out that there was a partial solution in this PR https://github.com/jenkinsci/ec2-plugin/pull/154, but it assumes that there is a SlaveTemplate to modify, where in our case we need to add new templates.
**Local Test Result:**
```
Tests run: 165, …
```
> Created method that would allow to programmatically add new slave templates to an EC2Cloud

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
> JENKINS-71554: Reconnect on "RequestExpired" exception

- README.md
- pom.xml
- src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
- src/test/resources/hudson/plugins/ec2/Ami.yml
- src/test/resources/hudson/plugins/ec2/BackwardsCompatibleConnectionStrategy.yml
- src/test/resources/hudson/plugins/ec2/EC2CloudEmpty.yml
- src/test/resources/hudson/plugins/ec2/Mac.yml
- src/test/resources/hudson/plugins/ec2/MacData.yml
- src/test/resources/hudson/plugins/ec2/MacDataExport.yml
- src/test/resources/hudson/plugins/ec2/Unix-withMinimumInstancesTimeRange.yml
- src/test/resources/hudson/plugins/ec2/Unix.yml
- src/test/resources/hudson/plugins/ec2/UnixData-withAltEndpointAndJavaPath.yml
- src/test/resources/hudson/plugins/ec2/UnixData.yml
- src/test/resources/hudson/plugins/ec2/UnixDataExport-withAltEndpointAndJavaPath.yml
- src/test/resources/hudson/plugins/ec2/UnixDataExport.yml
- src/test/resources/hudson/plugins/ec2/WindowsData.yml
Preparing for https://github.com/jenkinsci/jenkins/pull/8310 where cloud name changes will be done on a separate page
The use of the variable name cloudName in AmazonEC2Cloud forces jenkins core to have a special case of handling cloudName when it not a variable of Cloud.
https://github.com/jenkinsci/jenkins/blob/d41b0f5807923286ad33d4847af95e2c6c7c77ba/core/src/main/java/jenkins/agents/CloudSet.java#L229
manually created new AmazonEC2Cloud
test in config-as-code integration tests: https://github.com/jenkinsci/configuration-as-code-plugin/pull/2372/
```[tasklist]
```
> [JENKINS-71737] rename cloudName to name

- Jenkinsfile
- pom.xml
[JENKINS-72007](https://issues.jenkins.io/browse/JENKINS-72007) asks for support of new EC2 instance types that are available with newer versions of the AWS Java SDK.  I'm not a user of the AWS Java SDK, but there is a release of the new version of the API plugin that provides the new machine types.
* [EC2 pre-release from this pull request](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/ec2/1645.ve11a_2de7a_188/ec2-1645.ve11a_2de7a_188.hpi) depends on the released versions of [SDK minimal](https://plugins.jenkins.io/aws-java-sdk-minimal/releases/#version_1.12.586-413.v6a_6c3a_420126) and [SDK EC2](https://plugins.jenkins.io/aws-java-sdk-ec2/releases/#version_1.12.586-413.v6a_6c3a_420126).
* [SDK minimal](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/aws- …
> [JENKINS-72007] Support new AWS machine types

- README.md
This adds more explanatory text, and also a specific example of how to set `repo_upgrade: none` via `#cloud-config` in user data.
I spent a long time trying to modify the cloud-init config within the AMI before realising I could just set the 'User data' on the Jenkins Clouds config for the AMI, so hopefully this will help someone else too.
Also list other symptoms of the same problem when Docker is being used which results in `EOF` error messages - it took me quite a while to realise that this was due to Amazon Linux security patching so again hopefully this reference will help others facing the same issue.
This is a readme only change - however I have tested that this snippet of 'User Data' in the Jenkins Clouds AMI configuration successfully results in cloud-init not running the yum …
> Update readme with more details on Amazon Linux repo_upgrade race issue

- pom.xml
- src/spotbugs/excludesFilter.xml
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
Annotations for Nonnull, CheckForNull, and several others were proposed for Java as part of dormant Java specification request JSR-305. The proposal never became a part of standard Java.
Jenkins plugins should switch from using JSR-305 annotations to use Spotbugs annotations that provide the same semantics.
The [mailing list discussion](https://groups.google.com/g/jenkinsci-dev/c/uE1wwtVi1W0/m/gLxdEJmlBQAJ) from James Nord describes the affected annotations and why they should be replaced with annotations that are actively maintained.
The ["Improve a plugin" tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/replace-jsr-305-annotations/) provides instructions to perform this change.
An [OpenRewrite recipe](https://docs.openrewrite.org/recipes/jenkins/javaxannotationstospotbugs …
> Replace JSR-305 annotations with spotbugs annotations

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
This PR allowed us to mitigate an active incident. The previous behavior is as follows:
- terminate node is called
- updateComputerList calls updateComputer on every node
- updateComputer calls SlaveComputer.check which runs describeInstances if time is after nextCheckAfter
This isn't an issue when we are terminating less than 600 nodes. But since describeInstances take around 100ms. When UpdateComputerList is called, to update every node, the total duration will exceed the current hard coded value of 1 minutes. So every computer termination takes 1 min to finish, during this time Queue lock is taken so no new work can be accepted.
TESTING PLAN
Installed on our controllers, launched 800 nodes via minInstances, then set minInstances to 0. Instead of the controller locking up until it …
> JENKINS-73096 Create config for check interval and use the same default

- README.md
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/test/java/hudson/plugins/ec2/EC2CloudTest.java
Added functionallity that would allow programmatic update of SlaveTemplates, which can be done by specifying the "old" SlaveTemplate's description. In case a template with the provided description does not exist, an exception is thrown. This feature is useful when someone wants to manage the SlaveTemplates programatically via the Jenkins Script feature. 
[Added an Unit test for the new EC2Cloud method](https://github.com/drullar/ec2-plugin/blob/2d21ff4e9f7b7d14e3bbfd91bd34ce8bfe2d0412/src/test/java/hudson/plugins/ec2/EC2CloudTest.java#L40). Attached screenshot of local test execution
> Added support for programmatic update of a SlaveTemplate

- pom.xml
- src/main/resources/hudson/plugins/ec2/EC2Cloud/computerSet.jelly
- src/main/resources/hudson/plugins/ec2/EC2Cloud/provision.js
Fixes https://issues.jenkins.io/browse/JENKINS-73541
Replace YUI button with a more modern component, analogous to https://github.com/jenkinsci/credentials-plugin/pull/551 as part of the YUI removal initiative (https://issues.jenkins.io/browse/JENKINS-73539 )
Manually checked that clicking the dropdown button goes to the provision page with the correct parameters.
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Replace dropdown button to remove dependency on YUI

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
When provisioning a new EC2 instance, an `AmazonServiceException` with an error code `ExpiredToken` should be treated in the same way as an `AmazonServiceException` with an error code `RequestExpired`.
```
WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID 692686b6-bfdc-461b-b4f5-9b47e98ad418
com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: The security token included in the request is expired (Service: AWSSecurityTokenService; Status Code: 403; Error Code: ExpiredToken; Request ID: 18e279ff-8c67-4fdc-9327-bbd45bb8ec0a; Proxy: null)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(A …
```
> Reconnect to EC2 also when error code is ExpiredToken

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/resources/hudson/plugins/ec2/AmazonEC2Cloud/config-entries.jelly
- src/main/resources/hudson/plugins/ec2/EC2Cloud/help-roleArn.html
- src/main/resources/hudson/plugins/ec2/EC2Cloud/help-roleSessionName.html
- src/test/java/hudson/plugins/ec2/AmazonEC2CloudTest.java
[JENKINS-74945](https://issues.jenkins.io/browse/JENKINS-74945): 
The Role ARN was silently ignored if the session name was not provided:
* Role ARN is now used whenever it is not empty, if a Role Session Name is not provided "Jenkins will be used"
* Added a check and warning on Role Session Name to warn that it is recommended to set it otherwise "Jenkins" will be used if unset.
* Added help message
* Started a Jenkins controller
* Create an EC2 Cloud
* Specify a Role Arn that can be assumed, leave Session Name empty, and hit test connection
--> It works
* Specify a Role Arn that cannot be assumed, leave Session Name empty, and hit test connection
--> it works
* leave Role Arn and Session Name empty, and hit test connection
--> it works (to make sure that STS is not used )
> [JENKINS-74945] Use Role ARN when defined

- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2OndemandSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
- src/test/java/hudson/plugins/ec2/TemplateLabelsTest.java
- src/test/java/hudson/plugins/ec2/ssh/verifiers/SshHostKeyVerificationStrategyTest.java
- src/test/java/hudson/plugins/ec2/win/WinConnectionTest.java
Like #1023, makes it easier to read these tests by avoiding the use of deprecated constructors.
`mvn clean verify`
> Remove more usages of deprecated constructors in tests

- src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Fix for https://issues.jenkins.io/browse/JENKINS-75187
Two fixes:
- misplaced `}`
- in the `ServerKeyVerifier`, convert the key to `openSSH` format
Tested locally with:
- an empty init script
- all possible "Host Key Verification Strategy"
> [JENKINS-75187] Unable to Connect to Agents

- src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
Fix for https://issues.jenkins.io/browse/JENKINS-75230
Previously, the `init.sh` script was uploaded without the `write` permission. On Windows, this creates a `read-only` file. This read-only file is then impossible to replace when the end user wants to reuse the same node. This read-only file causes `scp` to get stuck.
All uploaded files (the init script ant the remoting jar) now have the `write` permissions set.
Users with version `1822.v87175d209b_b_5` or later using a Windows image and the `unix` launcher who upgrade the plugin will have to disable manually the read-only flag on the `init.sh` and `remoting.jar` located in the temporary folder of the Windows machine or, alternatively, delete the the files.
A dedicated AMI was created, based on `ami-0abaed814109888a5` (Microsoft …
> [JENKINS-75230] Fixes the use of an init script with Windows AMI using a Linux launcher

- src/main/java/hudson/plugins/ec2/ssh/EC2MacLauncher.java
- src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
- src/main/java/hudson/plugins/ec2/util/KeyHelper.java
- src/main/java/hudson/plugins/ec2/util/SSHClientHelper.java
- src/test/java/hudson/plugins/ec2/MockEC2Computer.java
- src/test/java/hudson/plugins/ec2/ssh/verifiers/SshHostKeyVerificationStrategyTest.java
- src/test/java/hudson/plugins/ec2/util/SSHClientHelperTest.java
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp256/config.xml
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp256/nodes/MockInstanceForTestHostKey/ssh-host-key.xml
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp384/config.xml
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp384/nodes/MockInstanceForTestHostKey/ssh-host-key.xml
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp521/config.xml
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ecdsaSha2Nistp521/nodes/MockInstanceForTestHostKey/ssh-host-key.xml
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ed25519/config.xml
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/ed25519/nodes/MockInstanceForTestHostKey/ssh-host-key.xml
- src/test/resources/hudson/plugins/ec2/util/SSHClientHelperTest/setupSshClientWithNoHostKey/config.xml
Fix for https://issues.jenkins.io/browse/JENKINS-75214
When a `HostKey` already exists for the `Computer`, the algorithm is used as the preferred one to initiate the connection.
Please note that, as for now, `mina` doesn't support `ssh-ed25519` out of the box. This support will be added in a future release: https://github.com/apache/mina-sshd/issues/657.
In the meantime, it is require to install https://plugins.jenkins.io/eddsa-api/ for `ssh-ed25519` to be supported.
Note: I moved `MockEC2Computer` to use it in `SSHClientHelperTest`
> [JENKINS-75214] Added prioritization of SSH host key algorithms

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/test/java/hudson/plugins/ec2/EC2CloudUnitTest.java
See [JENKINS-75589](https://issues.jenkins.io/browse/JENKINS-75589). The code that populates the regions in the UI was failing to populate the regions on some installations.
The old code, prior to adoption of AWS Java SDK v2, implicitly set the region to `us-east-1` by virtue of setting the endpoint to https://ec2.amazonaws.com which triggered a deprecated code path in the AWS Java SDK v1 to eventually assume a region of `us-east-1`. The deprecated code has been removed in AWS Java SDK v2. We were not setting a region explicitly, thus triggering [this logic](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/awscore/client/builder/AwsClientBuilder.html#region(software.amazon.awssdk.regions.Region)):
> Configure the region with which the SDK should communicate.
> 
> If this …
> [JENKINS-75589] Region is no longer being kept in the UI

- src/main/java/hudson/plugins/ec2/EC2RetentionStrategy.java
Prior to the AWS Java SDK v2 conversion, this used millisecond precision, but now it only uses second precision. This restores the original behavior.
CI build
> Millisecond precision in `EC2RetentionStrategy`

- src/main/java/hudson/plugins/ec2/CloudHelper.java
- src/main/java/hudson/plugins/ec2/EC2Cloud.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
I was made aware of a controller seeing this stack trace:
```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "software.amazon.awssdk.awscore.exception.AwsErrorDetails.errorCode()" is null
at PluginClassLoader for ec2//hudson.plugins.ec2.CloudHelper.getInstanceWithRetry(CloudHelper.java:31)
at PluginClassLoader for ec2//hudson.plugins.ec2.EC2Computer.getState(EC2Computer.java:200)
at PluginClassLoader for ec2//hudson.plugins.ec2.EC2RetentionStrategy.start(EC2RetentionStrategy.java:293)
at PluginClassLoader for ec2//hudson.plugins.ec2.EC2RetentionStrategy.start(EC2RetentionStrategy.java:50)
at hudson.model.AbstractCIBase.createNewComputerForNode(AbstractCIBase.java:193)
at hudson.model.AbstractCIBase.updateComputer(AbstractCIBase.java:154) …
```
> [JENKINS-75840] `NullPointerException` in `CloudHelper.getInstanceWithRetry`

- src/main/java/hudson/plugins/ec2/SpotConfiguration.java
Value string was comparted to enum name of SDKs InstanceType which never matches.
Fixed the issue by using AWS SDK internal method to get enumeration from string.
Relates to:  https://issues.jenkins.io/browse/JENKINS-75870.
> [JENKINS-75870] Fix issue resolving instance types while checking for current spot pricing

- src/main/java/hudson/plugins/ec2/ssh/EC2WindowsSSHLauncher.java
The "scp.exe" binary included in versions of OpenSSH greater than 9.5.0.0 do not accept paths using backslashes. 
`
validateCommandStatusCode(ScpHelper[ClientSessionImpl[Administrator@/X.X.X.X:22]])[scp -p -t -- C:\Windows\Temp\init.bat] advisory ACK=1: scp: error: unexpected filename: C:\Windows\Temp\init.bat for command=C0700 16 C:\Windows\Temp\init.bat 
`
Replacing the backslashes with forward slashes fixes the issue and also works with versions 9.5.0.0 and lower
Tested on Jenkins controller 2.519
Tested with agents:
Windows Server 2019, OpenSSH 8.9.1.0
Windows Server 2019, OpenSSH 9.5.0.0
Windows Server 2019, OpenSSH 9.5.4.1
Windows Server 2019, OpenSSH 9.8.3.0
Windows Server 2025, OpenSSH 9.5.4.1
> [JENKINS-75910] Unable to connect to Windows SSH instance using OpenSSH version greater than 9.5.0.0

- src/test/java/hudson/plugins/ec2/util/SSHCredentialHelper.java
Amending #498. `PrivateKeySource` is only even an interface you can implement for historical reasons: all implementations besides `DirectEntryPrivateKeySource` are deprecated. Noticed because of a warning in test output
```
WARNING	o.j.r.u.AnonymousClassWarnings#warn: Attempt to (de-)serialize anonymous class hudson.plugins.ec2.util.SSHCredentialHelper$1 in file:/…/ec2-plugin/target/test-classes/; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
```
> Simplification to `SSHCredentialHelper`

- src/main/java/hudson/plugins/ec2/ssh/EC2SSHLauncher.java
- src/test/java/hudson/plugins/ec2/ssh/InitScriptExecutionTest.java
Extracted from #1121.
While testing without #1125, as I recall (not sure exactly how to reproduce), I ran into some cases where the metadata inside the Jenkins controller was apparently out of date and there was an EC2 agent definition that corresponded to an instance which had already been terminated. This was not handled gracefully: the launch log went into a loop whereby it would claim that the hostname was not yet ready and it was going to sleep and try again in a few seconds. Clearly at this point the agent cannot be launched because the instance is gone, so it should fail early and clearly. With this patch, the agent definition gets deleted automatically.
> Fail `getEC2HostAddress` for a terminated instance

- src/main/java/hudson/plugins/ec2/EC2Cloud.java
Since migration to AWS SDK 2 and https://github.com/jenkinsci/ec2-plugin/pull/1021, theHttpclient proxy is always configured if Jenkins proxy is defined. Regardless of the list of Non proxy Hosts. Which is a regression.
This fixes the proxy support so that the list of non proxy hosts from the Jenkins Proxy configuration are properly used.
* Setup a squid proxy with deny to `*.amazonaws.com`
* In Jenkins, configure Jenkins Proxy and add `*.amazonaws.com` and `169.254.169.254` to the list of non proxy hosts
* Configure EC2 Cloud
* Use the Test Connection button
> [JENKINS-76021] Fix non proxy hosts support

- src/main/java/hudson/plugins/ec2/EC2AbstractSlave.java
- src/main/java/hudson/plugins/ec2/EC2OndemandSlave.java
- src/main/java/hudson/plugins/ec2/EC2SpotSlave.java
- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/main/java/hudson/plugins/ec2/util/MinimumInstanceChecker.java
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/config.jelly
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-terminateIdleDuringShutdown.html
- src/main/resources/hudson/plugins/ec2/SlaveTemplate/help-terminateSpareInstances.html
- src/test/java/hudson/plugins/ec2/EC2AbstractSlaveTest.java
- src/test/java/hudson/plugins/ec2/EC2RetentionStrategyTest.java
- src/test/java/hudson/plugins/ec2/MockEC2Computer.java
- src/test/java/hudson/plugins/ec2/ssh/InitScriptExecutionTest.java
Extracted from #1121.
While testing the spare instances feature I noticed that while the controller launches a pool of spare instances when it starts, it does not terminate them when it shuts down. If the controller is immediately restarted, this is not a big deal since they will be connected again, but it can leave a mess in a CloudBees CI HA controller where each replica has its own set of spare instances. #1115 will clean them up but it could take hours. With this patch, the spares are neatly cleaned up.
I needed to introduce a `Future` into the internal API to make sure that the termination request is processed before the web app is unloaded and class loading from plugins becomes impossible; otherwise the termination is unreliable and mostly does not work at all. This does clash a bit …
> Discard idle instances during shutdown

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
See: https://issues.jenkins.io/browse/JENKINS-75002
The issue with the plugin arises when the "Associate Public IP" checkbox is not selected. In this case, it neither sends the network interface nor the associatePublicIpAddress field, relying entirely on the subnet configuration.
`NetworkInterface` object was getting build only if & only if `allowPublicIp` value is `true` otherwise not.
Now irrespective `allowPublicIp` value, `NetworkInterface` object will get build.
1. Build is green.
2. Added 2 new unit tests which checks for existence of the `networkInterface` object irrespective of `allowedPublicIpAddress` values.
3. Tried provisioning the EC2 instance with changes & its launching the instance in both cases.
- Checked `Allow Public IP` : It launches the EC2 instance & connect to it. ✅ …
> Removed associatePublicIp check for building the NW interface obj

- src/main/java/hudson/plugins/ec2/SlaveTemplate.java
- src/test/java/hudson/plugins/ec2/SlaveTemplateTest.java
Reverts jenkinsci/ec2-plugin#1138
Reverting the changes as its causing the regression
https://issues.jenkins.io/browse/JENKINS-76068
> Revert "[JENKINS-75002] Removed associatePublicIp check for building the NW interface obj"

- src/main/java/hudson/plugins/ec2/ssh/EC2SSHLauncher.java
- src/main/java/hudson/plugins/ec2/ssh/verifiers/HostKeyHelper.java
- src/test/java/hudson/plugins/ec2/ssh/verifiers/SshHostKeyVerificationStrategyTest.java
- src/test/java/hudson/plugins/ec2/util/ConnectionExtension.java
* Reinstated tests that were disabled and fix them to test verifiers.
* Added scenario for different algorithm
* Fix a regression introduced in https://github.com/jenkinsci/ec2-plugin/pull/1141
* Only Unit Tests
* TODO: EC2 provisioning with different strategies
> [JENKINS-76083] Fix tests for SSH Verifiers + fix regression 
